@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.reflection.access.field"
    
    interface Getter
    interface Setter
    
    Getter <|-- FieldGetter
    class FieldGetter
    {
        --(constructors)--
        +FieldGetter(java.lang.reflect.Field)
    }
    
    Setter <|-- FieldSetter
    class FieldSetter
    {
        --(constructors)--
        +FieldSetter(java.lang.reflect.Field)
    }
    
@enduml

