@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.threading.locks"
    
    ReentrantLock <|-- Lock
    class Lock
    {
        --
        +void whileLocked(Runnable code)
        --(functional)--
        +T whileLocked(Code<T>)
    }
    
    class Monitor
    {
        --(thread)--
        +void await()
        +void signal()
    }
    
    ReentrantReadWriteLock <|-- ReadWriteLock
    class ReadWriteLock
    {
        --(constructors)--
        +ReadWriteLock()
        --(read)--
        +void read(Runnable code)
        +T read(Source<T> code)
        --(write)--
        +void write(Runnable code)
        +T write(Source<T> code)
    }
    
@enduml

