@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.matching.matchers"
    
    interface Matcher
    
    Matcher <|-- All
    class All<T>
    {
    }
    
    Matcher <|-- None
    class None<T>
    {
    }
    
    Matcher <|-- WithName
    class WithName<T>
    {
        --(constructors)--
        +WithName(Named)
        +WithName(String)
    }
    
    Matcher <|-- WithNameMatching
    class WithNameMatching<T>
    {
        --(constructors)--
        +WithNameMatching(Pattern)
    }
    
@enduml

