@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.reflection.property.filters.method"
    
    KivaKitProperties <|-- AllMethods
    class AllMethods
    {
        --(constructors)--
        +AllMethods(Set<Include>)
    }
    
    AllMethods <|-- NamedMethod
    class NamedMethod
    {
        --(constructors)--
        +NamedMethod(String)
    }
    
@enduml

