@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.threading.conditions"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- StateMachine
    class StateMachine<State>
    {
        --(constructors)--
        +StateMachine(State)
        +StateMachine(State, Receiver<State>)
        --
        +boolean is(State)
        +boolean transition(State from, State to)
        +State transitionTo(State to)
        --(thread)--
        +boolean transitionAndWait(State from, State to, State waitFor)
        +boolean transitionAndWait(State from, State to, State waitFor, Duration maximumWait)
        +boolean waitFor(State)
        +boolean waitFor(State, Duration maximumWait)
    }
    
    class StateWatcher<State>
    {
        --(thread)--
        +void signal(State)
        +WakeState waitFor(State desired, Duration maximumWaitTime)
        +WakeState waitFor(Predicate<State>)
        +WakeState waitFor(State desired)
        +WakeState waitFor(Predicate<State>, Duration maximumWaitTime)
    }
    
    class StateWatcher.WaitingThread
    {
    }
    
@enduml

