@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.interfaces.function"
    
    interface BooleanFunction<Value>
    {
        --(checks)--
        +boolean isTrue(Value)
    }
    
@enduml

