@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.collections.list"
    
    abstract BaseList
    
    interface Prependable
    interface AsString
    interface Addable
    interface Appendable
    interface RandomAccess
    interface List
    interface Indexable
    interface NewInstance
    interface CompressibleCollection
    
    NewInstance <|-- BaseList
    List <|-- BaseList
    Indexable <|-- BaseList
    Addable <|-- BaseList
    Appendable <|-- BaseList
    Prependable <|-- BaseList
    CompressibleCollection <|-- BaseList
    RandomAccess <|-- BaseList
    AsString <|-- BaseList
    abstract class BaseList<Element>
    {
        --(constructors)--
        #BaseList()
        #BaseList(List<Element>)
        #BaseList(Maximum)
        #BaseList(Maximum, List<Element>)
        --
        +String bulleted()
        +String bulleted(int indent)
        +long[] quantized()
        +void reverse()
        #void onOutOfRoom()
        #String separator()
        --(checks)--
        +boolean endsWith(BaseList<Element> that)
        +boolean startsWith(BaseList<Element> that)
        --(collection)--
        +boolean addAll(Element[] elements)
        +boolean addIfNotNull(Element)
        +BaseList<Element> appendAll(Element[] elements)
        +Element[] asArray(Class<Element> type)
        +StringList asStringList()
        +BaseList<Element> copy()
        +BaseList<Element> filtered(Matcher<Element>)
        +BaseList<Element> first(int count)
        +BaseList<Element> first(Count)
        +BaseList<Element> leftOf(int index)
        +BaseList<Target> mapped(Function<Element,Target> mapper)
        +Maximum maximumSize()
        +BaseList<Element> maybeReversed(boolean reverse)
        +Element removeLast()
        +BaseList<Element> reversed()
        +BaseList<Element> rightOf(int index)
        +BaseList<Element> sorted(Comparator<Element>)
        +BaseList<Element> sorted()
        +BaseList<Element> uniqued()
        +BaseList<Element> without(Matcher<Element>)
        #boolean checkSizeIncrease(int increase)
        --(lifecycle)--
        +String join()
    }
    
    class LinkedObjectList<T>
    {
        --
        +boolean replace(T object, T replacement)
        --(collection)--
        +Iterator<T> matching(Matcher<T>)
        +Collection<T> remove(Matcher<T>)
    }
    
    class Lists
    {
        --(collection)--
        +ArrayList<T> arrayList(T... objects)
    }
    
    BaseList <|-- ObjectList
    class ObjectList<Element>
    {
        --(constructors)--
        +ObjectList()
        +ObjectList(Maximum)
        --(collection)--
        +StringList asStringList(StringConverter<Element>)
        +ObjectList<T> emptyList()
        +ObjectList<T> objectList(Iterable<T> values)
        +ObjectList<T> objectList(Maximum maximumSize, T... objects)
        +ObjectList<T> objectList(Iterable<Quantizable> values, LongMapFactory<T>)
        +ObjectList<T> objectList(T... objects)
        +ObjectList<T> objectListFromInts(IntMapFactory<T>, int... values)
        +ObjectList<T> objectListFromLongs(LongMapFactory<T>, long... values)
        +ObjectList<ObjectList<Element>> partition(Count partitions)
    }
    
    ObjectList <|-- StringList
    class StringList
    {
        --(constructors)--
        +StringList()
        +StringList(Iterable<?>)
        +StringList(Iterator<?>)
        +StringList(Maximum)
        +StringList(Maximum, Iterable<?>)
        +StringList(Maximum, Iterator<?>)
        +StringList(Maximum, String)
        --
        +String titledBox(String title)
        #String objectToString(Object)
        --(collection)--
        +StringList add(String message, Object... arguments)
        +ObjectList<T> asObjectList(StringConverter<T>)
        +String[] asStringArray()
        +VariableMap<String> asVariableMap()
        +StringList doubleQuoted()
        +StringList indented(int spaces)
        +Count longest()
        +StringList numbered()
        +StringList prefixedWith(String prefix)
        +StringList println()
        +StringList repeat(String text, int times)
        +StringList singleQuoted()
        +StringList split(String, String delimiter)
        +StringList split(Maximum maximumSize, String, char delimiter)
        +StringList split(Maximum maximumSize, String text, String delimiter)
        +StringList split(String, char delimiter)
        +StringList splitOnPattern(String text, String pattern)
        +StringList stringList(Iterable<T> values, StringConverter<T>)
        +StringList stringList(Iterable<T> values)
        +StringList stringList(String... strings)
        +StringList stringList(Maximum maximumSize, String... strings)
        +StringList titledBox(Listener, String title)
        +StringList words(String text)
    }
    
@enduml

