@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.types"
    
    class Classes
    {
        --
        +String simpleTopLevelClass(Class<?> type)
        --(checks)--
        +boolean isPrimitive(Class<?> type)
        --(naming)--
        +Class<T> forName(ClassLoader, String name)
        +Class<T> forName(String name)
        +String simpleName(Class<?> type)
        --(network)--
        +URI resourceUri(Class<?> base, String path)
        +URL resourceUrl(Class<?> base, String path)
        --(read)--
        +InputStream openResource(Class<?> base, String path)
    }
    
@enduml

