@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.values.version"
    
    interface Versioned
    interface NamedObject
    
    class Version
    {
        --(constructors)--
        #Version()
        #Version(int, int, int, Release)
        --
        +int major()
        +int minor()
        +int patch()
        +Release release()
        --(checks)--
        +boolean hasPatch()
        +boolean hasRelease()
        +boolean isNewerThan(Version that)
        +boolean isNewerThanOrEqualTo(Version that)
        +boolean isOlderThan(Version that)
        +boolean isOlderThanOrEqualTo(Version that)
        --(identity)--
        +Version newer(Version that)
        +Version of(int major, int minor)
        +Version of(int major, int minor, int patch)
        +Version of(int major, int minor, int patch, Release)
        +Version older(Version that)
        +Version parse(String text)
        +Version withoutPatch()
        +Version withoutRelease()
    }
    
    interface Versioned
    {
        --(identity)--
        +Version version()
    }
    
    NamedObject <|-- VersionedObject
    Versioned <|-- VersionedObject
    class VersionedObject<T>
    {
        --(constructors)--
        +VersionedObject(T)
        +VersionedObject(Version, T)
        --
        +T get()
    }
    
@enduml

