@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.collections.set"
    
    abstract BaseSet
    
    interface Sized
    interface AsString
    interface Set
    interface Addable
    interface NewInstance
    
    Set <|-- BaseSet
    NewInstance <|-- BaseSet
    Sized <|-- BaseSet
    Addable <|-- BaseSet
    AsString <|-- BaseSet
    abstract class BaseSet<Element>
    {
        --(constructors)--
        #BaseSet()
        +BaseSet(Maximum)
        +BaseSet(Maximum, Set<Element>)
        +BaseSet(Set<Element>)
        --(collection)--
        +Element first()
        +Iterable<Element> matching(Matcher<Element>)
        +Count maximumSize()
        #boolean checkSize(int increase)
    }
    
    BaseSet <|-- ObjectSet
    class ObjectSet<T>
    {
        --(constructors)--
        +ObjectSet()
        +ObjectSet(Maximum)
        +ObjectSet(Maximum, Set<T>)
    }
    
    class Sets
    {
        --
        +Set<T> identitySet()
        +Set<T> nonNull(Set<T>)
        +Set<T> of(T... list)
        +Set<T> union(Set<T> a, Set<T> b)
        --(collection)--
        +Set<T> empty()
        +T first(Set<T>)
        +Set<T> fromIterable(Iterable<T>)
        +HashSet<T> hashset(Collection<T>)
        +HashSet<T> hashset(T... values)
        --(filesystem)--
        +Set<Value> copy(Factory<Set<Value>>, Set<Value>)
        +Set<Value> deepCopy(Factory<Set<Value>>, Set<Value>, Function<Value,Value> clone)
    }
    
@enduml

