@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.messaging.broadcasters"
    
    interface PackagePathed
    interface Broadcaster
    
    AudienceMember o-- Listener
    AudienceMember o-- Filter
    class AudienceMember
    {
        --(messaging)--
        +Listener listener()
        +void receive(Transmittable message)
    }
    
    Broadcaster <|-- Multicaster
    PackagePathed <|-- Multicaster
    Multicaster "1" o-- "*" AudienceMember
    class Multicaster
    {
        --(constructors)--
        #Multicaster()
        #Multicaster(Multicaster)
        #Multicaster(String)
        +Multicaster(Class<?>)
        +Multicaster(String, Class<?>)
        --(messaging)--
        +boolean isDeaf()
        +String listenerTree()
        +List<Listener> listeners()
    }
    
@enduml

