@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.values.count"
    
    abstract BaseStringConverter
    
    interface Countable
    interface AsString
    interface Ranged
    interface Comparable
    interface Serializable
    interface Listener
    interface Contains
    interface ByteSized
    interface Quantizable
    
    Count <|-- BitCount
    class BitCount
    {
        --(constructors)--
        #BitCount()
        #BitCount(long)
        --
        +long mask()
        --(collection)--
        +BitCount bitCount(long count)
        +BitCount bitCount(T[] values)
        +BitCount maximum(BitCount that)
        +BitCount minimum(BitCount that)
        +BitCount minus(BitCount)
        +BitCount perByte()
        +BitCount perCharacter()
        +BitCount perInteger()
        +BitCount perLong()
        +BitCount perShort()
        +BitCount times(BitCount)
        +BitCount toRepresent(long value)
        +long values()
        --(math)--
        +long maximumSigned()
        +long maximumUnsigned()
        +long minimumSigned()
    }
    
    Count <|-- Bytes
    ByteSized <|-- Bytes
    class Bytes
    {
        --(constructors)--
        #Bytes()
        --
        +void reverse(byte[] array)
        +void reverse(byte[] array, int fromIndex, int toIndex)
        --(checks)--
        +boolean isGreaterThan(Bytes that)
        +boolean isGreaterThanOrEqualTo(Bytes that)
        +boolean isLessThan(Bytes that)
        +boolean isLessThanOrEqualTo(Bytes that)
        --(conversion)--
        +double asGigabytes()
        +double asKilobytes()
        +double asMegabytes()
        +double asTerabytes()
        --(math)--
        +Percent percentOf(Bytes that)
        --(primitive)--
        +Bytes add(Bytes that)
        +long asBytes()
        +Bytes bytes(long bytes)
        +Bytes bytes(Count)
        +Bytes bytes(double bytes)
        +Bytes gigabytes(double gigabytes)
        +Bytes gigabytes(long gigabytes)
        +Bytes kilobytes(long kilobytes)
        +Bytes kilobytes(double kilobytes)
        +Bytes maximum(Bytes that)
        +Bytes megabytes(double megabytes)
        +Bytes megabytes(long megabytes)
        +Bytes minimum(Bytes that)
        +Bytes minus(Bytes that)
        +Bytes parse(Listener, String bytes)
        +Bytes parse(String bytes)
        +Bytes terabytes(long terabytes)
        +Bytes terabytes(double terabytes)
    }
    
    Countable <|-- ConcurrentMutableCount
    Listener <|-- ConcurrentMutableCount
    class ConcurrentMutableCount
    {
        --(constructors)--
        +ConcurrentMutableCount()
        +ConcurrentMutableCount(long)
        --
        +long get()
        +void set(long count)
        --(checks)--
        +boolean isGreaterThan(ConcurrentMutableCount that)
        +boolean isLessThan(ConcurrentMutableCount that)
        +boolean isZero()
        --(collection)--
        +void clear()
        --(conversion)--
        +Count asCount()
        +int asInt()
        +long asLong()
        --(math)--
        +long add(long that)
        +long add(Count that)
        +long decrement()
        +long increment()
        +Percent percentOf(Count total)
    }
    
    BaseStringConverter <|-- Maximum.Converter
    class Maximum.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    BaseStringConverter <|-- Bytes.Converter
    class Bytes.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    BaseStringConverter <|-- Count.Converter
    class Count.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    BaseStringConverter <|-- Minimum.Converter
    class Minimum.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    Countable <|-- Count
    Comparable <|-- Count
    Quantizable <|-- Count
    AsString <|-- Count
    Serializable <|-- Count
    class Count
    {
        --(constructors)--
        #Count()
        #Count(long)
        --
        +long get()
        --(checks)--
        +boolean isEvenlyDividedBy(Count that)
        +boolean isGreaterThan(Count that)
        +boolean isGreaterThanOrEqualTo(Count that)
        +boolean isLessThan(Count that)
        +boolean isLessThanOrEqualTo(Count that)
        +boolean isMaximum()
        --(collection)--
        +BitCount asBitCount()
        +Count asCount()
        +BitCount bitsToRepresent()
        +Count ceiling(int digits)
        +Count count(Iterable<?>, Count maximum)
        +Count count(long value)
        +Count count(T[] values)
        +Count count(Iterator<?>, Count maximum)
        +Count count(Collection<?>)
        +Count count(Iterable<?>)
        +Count count(Iterator<?>)
        +Count decremented()
        +Count dividedBy(Count divisor)
        +Count dividedBy(long divisor)
        +Count floor(int digits)
        +Count incremented()
        +Count maximum(Count that)
        +Count minimum(Count that)
        +Count minus(long count)
        +Count minus(Count)
        +Count minusOne()
        +byte[] newByteArray()
        +char[] newCharArray()
        +double[] newDoubleArray()
        +float[] newFloatArray()
        +int[] newIntArray()
        +long[] newLongArray()
        +T[] newObjectArray()
        +short[] newShortArray()
        +String[] newStringArray()
        +Count nextPrime()
        +Count parse(String value)
        +Count percent(Percent percentage)
        +Count plus(long count)
        +Count plus(Count)
        +Count plusOne()
        +Count roundUpToPowerOfTwo()
        +Count times(Count)
        +Count times(long count)
        +Count times(Percent percentage)
        +Count times(double multiplier)
        #Count onNewInstance(long value)
        --(conversion)--
        +Estimate asEstimate()
        +int asInt()
        +long asLong()
        +Maximum asMaximum()
        +Minimum asMinimum()
        +String toCommaSeparatedString()
        +String toSimpleString()
        --(iteration)--
        +void loop(Loopable code)
        +void loop(Runnable code)
        +void loop(int times, Loopable code)
        --(math)--
        +boolean dividesEvenlyBy(Count value)
        +Percent percentOf(Count total)
        --(primitive)--
        +void forEachByte(Consumer<Byte>)
        +void forEachInteger(Consumer<Integer>)
        +void forEachLong(Consumer<Long>)
        +void forEachShort(Consumer<Short>)
    }
    
    Count <|-- Estimate
    AsString <|-- Estimate
    class Estimate
    {
        --(constructors)--
        #Estimate()
        #Estimate(long)
        --
        +Estimate estimate(Collection<?>)
        +Estimate estimate(long value)
        +Estimate estimate(Iterator<?>)
        +Estimate estimate(T[] values)
        +Estimate estimate(Iterable<?>)
        --(collection)--
        +Estimate add(Estimate that)
        --(parsing)--
        +Estimate parse(String value)
    }
    
    Contains <|-- LongRange
    class LongRange
    {
        --(constructors)--
        #LongRange()
        +LongRange(long, long)
        --
        +Long constrainTo(Long value)
        --(math)--
        +Long maximum(Long that)
        +Long maximum()
        +Long minimum(Long that)
        +Long minimum()
    }
    
    Count <|-- Maximum
    class Maximum
    {
        --(constructors)--
        #Maximum()
        #Maximum(long)
        --(math)--
        +Maximum maximum(Collection<?>)
        +Maximum maximum(long value)
        +Maximum maximum(Iterator<?>)
        +Maximum maximum(Iterable<?>)
        +Maximum maximum(T[] values)
        +Maximum parse(String value)
    }
    
    Count <|-- Minimum
    class Minimum
    {
        --(constructors)--
        #Minimum()
        #Minimum(long)
        --(math)--
        +Minimum minimum(long value)
        +Minimum minimum(Collection<?>)
        +Minimum minimum(Iterable<?>)
        +Minimum minimum(T[] values)
        +Minimum minimum(Iterator<?>)
        +Minimum parse(String value)
    }
    
    Countable <|-- MutableCount
    Comparable <|-- MutableCount
    Listener <|-- MutableCount
    class MutableCount
    {
        --(constructors)--
        +MutableCount()
        +MutableCount(long)
        --
        +long get()
        +void set(long count)
        --(checks)--
        +boolean isGreaterThan(MutableCount that)
        +boolean isLessThan(MutableCount that)
        +boolean isZero()
        --(collection)--
        +Count asCount()
        +void clear()
        --(math)--
        +long decrement()
        +long increment()
        +long minus(long that)
        +Percent percentOf(Count total)
        +long plus(long that)
        +long plus(Count that)
        --(primitive)--
        +long asLong()
    }
    
    Ranged <|-- Range
    class Range<T>
    {
        --(constructors)--
        +Range(T, T)
    }
    
@enduml

