@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.reflection.access"
    
    interface Named
    Named <|-- Getter
    interface Getter
    {
        --
        +T annotation(Class<T> annotationType)
        +Object get(Object)
        +Class<?> type()
    }
    
    interface Named
    Named <|-- Setter
    interface Setter
    {
        --
        +T annotation(Class<T> annotationType)
        +Class<?> type()
        --(messaging)--
        +Message set(Object, Object value)
    }
    
@enduml

