@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.kernel.language.modules"
    
    class ModuleResource
    {
        --(constructors)--
        #ModuleResource(PackagePath, URI)
        --
        +ModuleResource moduleResource(ModuleReference, URI)
        --(collection)--
        +Time lastModified()
        +Bytes size()
        --(network)--
        +URI uri()
        --(path)--
        +Path fileNameAsJavaPath()
        +Path javaPath()
        +PackagePath packagePath()
    }
    
    class Modules
    {
        --
        +ModuleResource resource(StringPath)
        --(collection)--
        +void addSearchScope(String prefix)
        +List<ModuleResource> allNestedResources(PackagePath _package)
        +List<ModuleResource> nestedResources(PackagePath _package, Matcher<ModuleResource>)
        +List<ModuleResource> nestedResources(PackagePath _package)
        +List<ModuleResource> resources(PackagePath _package)
    }
    
@enduml

