@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.serialization.json"
    
    interface Factory
    interface GsonSerializer
    
    Factory <|-- GsonFactory
    abstract class GsonFactory
    {
        --
        +void prettyPrinting(boolean pretty)
        #StringConverterGsonSerializer<T> serializer(StringConverter<T>)
        --(collection)--
        #void addSerializer(GsonBuilder, Class<T> type, GsonSerializer<T>)
        #GsonBuilder addSerializers(GsonBuilder)
    }
    
    interface JsonDeserializer<T>
    interface JsonSerializer<T>
    JsonSerializer <|-- GsonSerializer
    JsonDeserializer <|-- GsonSerializer
    interface GsonSerializer<T>
    {
    }
    
    GsonSerializer <|-- PrimitiveGsonSerializer
    abstract class PrimitiveGsonSerializer<T, Primitive>
    {
        --(constructors)--
        #PrimitiveGsonSerializer(Class<Primitive>)
        --(conversion)--
        #T toObject(Primitive scalar)
        #Primitive toPrimitive(T object)
    }
    
    GsonSerializer <|-- StringConverterGsonSerializer
    class StringConverterGsonSerializer<T>
    {
        --(constructors)--
        +StringConverterGsonSerializer(StringConverter<T>)
    }
    
@enduml

