@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.application.project"
    
    Project <|-- CoreApplicationProject
    class CoreApplicationProject
    {
        --(constructors)--
        #CoreApplicationProject()
        --
        +CoreApplicationProject get()
    }
    
@enduml

