@startuml

    !include ../lexakai.theme
    
    title "Service Client"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- ServiceRegistryClient
    ServiceRegistryClient --> ApplicationIdentifier : "discovers applications"
    ServiceRegistryClient --> Result : "returns"
    ServiceRegistryClient --> Scope : "searches within"
    ServiceRegistryClient --> Service : "discovers services"
    class ServiceRegistryClient
    {
        --(lookup)--
        +Result<Service> register(Scope, ServiceType, ServiceMetadata)
        +Result<Service> register(Service)
        --(network)--
        +Result<Boolean> sendNetworkRegistryUpdate(Service)
        --(search)--
        +Result<Set<ApplicationIdentifier>> discoverApplications(Scope)
        +Result<Service> discoverPortService(Port)
        +Result<Set<Service>> discoverServices(Scope, ApplicationIdentifier, ServiceType)
        +Result<Set<Service>> discoverServices(Scope, ServiceType)
        +Result<Set<Service>> discoverServices(Scope)
        +Result<Set<Service>> discoverServices(Scope, ApplicationIdentifier)
    }
    
@enduml

