@startuml

    !include ../lexakai.theme
    
    title "service.project"
    
    Project <|-- CoreNetworkServiceProject
    class CoreNetworkServiceProject
    {
        --(network)--
        +CoreNetworkServiceProject get()
    }
    
    KryoSerialization <|-- NetworkServiceKryoSerialization
    class NetworkServiceKryoSerialization
    {
        --(constructors)--
        +NetworkServiceKryoSerialization(Listener)
    }
    
@enduml

