
@startuml

    !include ../../lexakai.theme

    title "KivaKit Project Dependencies"

    legend top
        Simplified diagram of top-level project dependencies
    endlegend

    artifact tdk_core
    artifact tdk_data
    artifact tdk_filesystems
    artifact tdk_graph
    artifact tdk_josm
    artifact tdk_lexakai_annotations
    artifact tdk_logs
    artifact tdk_map
    artifact tdk_navigation
    artifact tdk_tools
    artifact tdk_ui
    artifact tdk_utilities
    artifact tdk_web

    tdk_core -up-> tdk_lexakai_annotations

    tdk_data -up-> tdk_core
    tdk_web -right-> tdk_core
    tdk_filesystems -left-> tdk_core
    tdk_ui -left-> tdk_core
    tdk_logs -right-> tdk_core
    tdk_map -up-> tdk_core
    tdk_utilities -up-> tdk_core

    tdk_graph -up-> tdk_map
    tdk_graph -up-> tdk_data
    tdk_graph -up-> tdk_utilities

    tdk_josm -up-> tdk_graph
    tdk_navigation -up-> tdk_graph
    tdk_tools -up-> tdk_graph

@enduml
