@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.filesystems.s3fs.project"
    
    Project <|-- FileSystemsS3FsProject
    class FileSystemsS3FsProject
    {
        --(constructors)--
        #FileSystemsS3FsProject()
        --(filesystem)--
        +FileSystemsS3FsProject get()
    }
    
@enduml

