@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.formats.csv.project"
    
    Project <|-- DataFormatsCsvProject
    class DataFormatsCsvProject
    {
        --(constructors)--
        #DataFormatsCsvProject()
        --
        +DataFormatsCsvProject get()
    }
    
@enduml

