@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.client"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- ServiceRegistryClient
    ServiceRegistryClient --> ApplicationIdentifier : "discovers applications"
    ServiceRegistryClient --> Provider.Service : "discovers services"
    ServiceRegistryClient --> Result : "returns"
    ServiceRegistryClient --> Scope : "searches within"
    class ServiceRegistryClient
    {
        --(constructors)--
        +ServiceRegistryClient()
        --(identity)--
        +Version version()
        --(lookup)--
        +Result<Service> register(Scope, ServiceType, ServiceMetadata)
        +Result<Service> register(Service)
        --(network)--
        +Result<Boolean> sendNetworkRegistryUpdate(Service)
        --(search)--
        +Result<Set<ApplicationIdentifier>> discoverApplications(Scope)
        +Result<Service> discoverPortService(Port)
        +Result<Set<Service>> discoverServices(Scope, ApplicationIdentifier, ServiceType)
        +Result<Set<Service>> discoverServices(Scope, ServiceType)
        +Result<Set<Service>> discoverServices(Scope)
        +Result<Set<Service>> discoverServices(Scope, ApplicationIdentifier)
    }
    
    class ServiceRegistryClientSettings
    {
        --
        +Resourceful serverJar()
        --(network)--
        +ServiceRegistryClientSettings accessTimeout(Duration timeout)
        +Duration accessTimeout()
        --(service)--
        +ServiceRegistryClientSettings serverJar(Resourceful location)
    }
    
@enduml

