@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.client.project"
    
    Project <|-- ServiceClientProject
    class ServiceClientProject
    {
        --(constructors)--
        #ServiceClientProject()
        --(service)--
        +ServiceClientProject get()
    }
    
@enduml

