@startuml

    !include ../lexakai/lexakai.theme
    
    title "kivakit-service-client"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact jackson_core
    artifact jackson_databind
    artifact jackson_module_jaxb_annotations
    artifact gson
    artifact kivakit_build_metadata
    artifact kivakit_core_application
    artifact kivakit_core_collections
    artifact kivakit_core_commandline
    artifact kivakit_core_configuration
    artifact kivakit_core_kernel
    artifact kivakit_core_network_core
    artifact kivakit_core_network_http
    artifact kivakit_core_resource
    artifact kivakit_core_security
    artifact kivakit_core_serialization_core
    artifact kivakit_core_serialization_jersey_json
    artifact kivakit_core_serialization_json
    artifact kivakit_core_serialization_kryo
    artifact kivakit_core_test
    artifact kivakit_service_client
    artifact kivakit_service_registry
    artifact lexakai_annotations
    artifact commons_codec
    artifact commons_logging
    artifact kryo_serializers
    artifact swagger_annotations
    artifact jakarta_activation_api
    artifact jakarta_annotation_api
    artifact jakarta_ws_rs_api
    artifact jakarta_xml_bind_api
    artifact junit
    artifact httpclient
    artifact httpcore
    artifact aopalliance_repackaged
    artifact jakarta_inject
    artifact hk2_api
    artifact hk2_locator
    artifact hk2_utils
    artifact osgi_resource_locator
    artifact jersey_client
    artifact jersey_common
    artifact jersey_entity_filtering
    artifact jersey_hk2
    artifact jersey_media_json_jackson
    artifact hamcrest_core
    artifact javassist
    artifact annotations
    artifact objenesis
    artifact asm
    hk2_locator --> aopalliance_repackaged
    hk2_locator --> hk2_api
    hk2_locator --> hk2_utils
    httpclient --> commons_codec
    httpclient --> commons_logging
    httpclient --> httpcore
    jackson_databind --> jackson_core
    jackson_module_jaxb_annotations --> jakarta_activation_api
    jackson_module_jaxb_annotations --> jakarta_xml_bind_api
    jersey_client --> jakarta_inject
    jersey_client --> jakarta_ws_rs_api
    jersey_client --> jersey_common
    jersey_common --> jakarta_annotation_api
    jersey_common --> osgi_resource_locator
    jersey_hk2 --> hk2_locator
    jersey_hk2 --> javassist
    jersey_media_json_jackson --> jackson_annotations
    jersey_media_json_jackson --> jackson_databind
    jersey_media_json_jackson --> jackson_module_jaxb_annotations
    jersey_media_json_jackson --> jersey_entity_filtering
    junit --> hamcrest_core
    kivakit_core_application --> kivakit_core_commandline
    kivakit_core_application --> kivakit_core_configuration
    kivakit_core_collections --> kivakit_core_serialization_kryo
    kivakit_core_commandline --> kivakit_core_kernel
    kivakit_core_kernel --> annotations
    kivakit_core_kernel --> junit
    kivakit_core_kernel --> kivakit_build_metadata
    kivakit_core_kernel --> lexakai_annotations
    kivakit_core_kernel --> swagger_annotations
    kivakit_core_network_core --> kivakit_core_security
    kivakit_core_network_http --> httpclient
    kivakit_core_network_http --> kivakit_core_resource
    kivakit_core_resource --> kivakit_core_collections
    kivakit_core_resource --> kivakit_core_serialization_core
    kivakit_core_security --> kivakit_core_test
    kivakit_core_serialization_jersey_json --> kivakit_core_serialization_json
    kivakit_core_serialization_json --> gson
    kivakit_core_serialization_kryo --> kryo
    kivakit_core_serialization_kryo --> kryo_serializers
    kivakit_service_client --> jersey_client
    kivakit_service_client --> jersey_hk2
    kivakit_service_client --> jersey_media_json_jackson
    kivakit_service_client --> kivakit_core_network_http
    kivakit_service_client --> kivakit_service_registry
    kivakit_service_registry --> kivakit_core_application
    kivakit_service_registry --> kivakit_core_network_core
    kivakit_service_registry --> kivakit_core_serialization_jersey_json
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    
@enduml
