
@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.filesystems.hdfs.project.lexakai.diagrams"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramHdfs
    class DiagramHdfs
    {
    }
    
@enduml

