@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.filesystems.hdfs.project"
    
    Project <|-- FileSystemsHdfsProject
    class FileSystemsHdfsProject
    {
        --(constructors)--
        #FileSystemsHdfsProject()
        --(filesystem)--
        +FileSystemsHdfsProject get()
    }
    
@enduml

