@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.server.webapp.pages.home"
    
    ServiceRegistryWebPage <|-- HomePage
    class HomePage
    {
        --(constructors)--
        +HomePage()
    }
    
    Panel <|-- ServicePanel
    class ServicePanel
    {
        --(constructors)--
        +ServicePanel(String, WebMarkupContainer, IModel<Service>)
    }
    
@enduml

