@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.server.project"
    
    Project <|-- ServiceRegistryServerProject
    class ServiceRegistryServerProject
    {
        --(constructors)--
        #ServiceRegistryServerProject()
        --(service)--
        +ServiceRegistryServerProject get()
    }
    
@enduml

