@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.service.registry.server.rest"
    
    JettyJerseyRestApplication <|-- ServiceRegistryRestApplication
    class ServiceRegistryRestApplication
    {
        --(constructors)--
        +ServiceRegistryRestApplication()
    }
    
    JettyJerseyRestResource <|-- ServiceRegistryRestResource
    class ServiceRegistryRestResource
    {
        --(extension points)--
        +DiscoverApplicationsResponse onDiscoverApplications(DiscoverApplicationsRequest)
        +DiscoverPortServiceResponse onDiscoverPortService(DiscoverPortServiceRequest)
        +DiscoverServicesResponse onDiscoverServices(DiscoverServicesRequest)
        +NetworkRegistryUpdateResponse onNetworkRegistryUpdate(NetworkRegistryUpdateRequest)
        +RegisterServiceResponse onRegisterService(RegisterServiceRequest)
        +RenewServiceResponse onRenewService(RenewServiceRequest)
        +Response onVersion()
    }
    
@enduml

