@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.server.rest"
    
    abstract BaseRestResource
    abstract BaseRestApplication
    
    BaseRestApplication <|-- ServiceRegistryRestApplication
    class ServiceRegistryRestApplication
    {
        --(constructors)--
        +ServiceRegistryRestApplication()
    }
    
    BaseRestResource <|-- ServiceRegistryRestResource
    class ServiceRegistryRestResource
    {
        --(extension points)--
        +DiscoverApplicationsResponse onDiscoverApplications(DiscoverApplicationsRequest)
        +DiscoverPortServiceResponse onDiscoverPortService(DiscoverPortServiceRequest)
        +DiscoverServicesResponse onDiscoverServices(DiscoverServicesRequest)
        +NetworkRegistryUpdateResponse onNetworkRegistryUpdate(NetworkRegistryUpdateRequest)
        +RegisterServiceResponse onRegisterService(RegisterServiceRequest)
        +RenewServiceResponse onRenewService(RenewServiceRequest)
        +Response onVersion()
    }
    
@enduml

