@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.server.webapp"
    
    WebApplication <|-- ServiceRegistryWebApplication
    class ServiceRegistryWebApplication
    {
    }
    
    WebPage <|-- ServiceRegistryWebPage
    class ServiceRegistryWebPage
    {
        --(constructors)--
        +ServiceRegistryWebPage()
    }
    
@enduml

