@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.service-server"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact jackson_core
    artifact jackson_databind
    artifact jackson_dataformat_yaml
    artifact jackson_datatype_jsr310
    artifact jackson_jaxrs_base
    artifact jackson_jaxrs_json_provider
    artifact jackson_module_jaxb_annotations
    artifact openjson
    artifact gson
    artifact wicket_jquery_ui_core
    artifact wicket_jquery_ui
    artifact com_telenav_lexakai_annotations
    artifact com_telenav_tdk_build_metadata
    artifact com_telenav_tdk_core_application
    artifact com_telenav_tdk_core_collections
    artifact com_telenav_tdk_core_commandline
    artifact com_telenav_tdk_core_configuration
    artifact com_telenav_tdk_core_kernel
    artifact com_telenav_tdk_core_network_core
    artifact com_telenav_tdk_core_network_http
    artifact com_telenav_tdk_core_resource
    artifact com_telenav_tdk_core_security
    artifact com_telenav_tdk_core_test
    artifact com_telenav_tdk_serialization_core
    artifact com_telenav_tdk_serialization_jersey_json
    artifact com_telenav_tdk_serialization_json
    artifact com_telenav_tdk_serialization_kryo
    artifact com_telenav_tdk_service_client
    artifact com_telenav_tdk_service_registry
    artifact com_telenav_tdk_service_server
    artifact com_telenav_tdk_web_jersey
    artifact com_telenav_tdk_web_jetty
    artifact com_telenav_tdk_web_swagger
    artifact com_telenav_tdk_web_wicket
    artifact commons_codec
    artifact commons_fileupload
    artifact commons_io
    artifact commons_logging
    artifact kryo_serializers
    artifact classgraph
    artifact swagger_annotations
    artifact swagger_core
    artifact swagger_integration
    artifact swagger_jaxrs2
    artifact swagger_models
    artifact jakarta_activation_api
    artifact jakarta_annotation_api
    artifact jakarta_validation_api
    artifact jakarta_ws_rs_api
    artifact jakarta_xml_bind_api
    artifact javax_servlet_api
    artifact junit
    artifact commons_collections4
    artifact commons_lang3
    artifact httpclient
    artifact httpcore
    artifact wicket_core
    artifact wicket_extensions
    artifact wicket_request
    artifact wicket_util
    artifact jdk_serializable_functional
    artifact jetty_http
    artifact jetty_io
    artifact jetty_security
    artifact jetty_server
    artifact jetty_servlet
    artifact jetty_util_ajax
    artifact jetty_util
    artifact jetty_webapp
    artifact jetty_xml
    artifact aopalliance_repackaged
    artifact jakarta_inject
    artifact hk2_api
    artifact hk2_locator
    artifact hk2_utils
    artifact osgi_resource_locator
    artifact jersey_container_servlet_core
    artifact jersey_container_servlet
    artifact jersey_client
    artifact jersey_common
    artifact jersey_server
    artifact jersey_entity_filtering
    artifact jersey_hk2
    artifact jersey_media_json_jackson
    artifact hamcrest_core
    artifact javassist
    artifact annotations
    artifact objenesis
    artifact asm
    artifact slf4j_api
    artifact swagger_ui
    artifact snakeyaml
    com_telenav_tdk_core_application --> com_telenav_tdk_core_commandline
    com_telenav_tdk_core_application --> com_telenav_tdk_core_configuration
    com_telenav_tdk_core_kernel --> annotations
    com_telenav_tdk_core_kernel --> com_telenav_lexakai_annotations
    com_telenav_tdk_core_kernel --> com_telenav_tdk_build_metadata
    com_telenav_tdk_core_network_core --> com_telenav_tdk_core_security
    com_telenav_tdk_core_network_http --> httpclient
    com_telenav_tdk_core_resource --> com_telenav_tdk_core_collections
    com_telenav_tdk_core_security --> com_telenav_tdk_core_test
    com_telenav_tdk_core_test --> com_telenav_tdk_serialization_core
    com_telenav_tdk_core_test --> com_telenav_tdk_serialization_kryo
    com_telenav_tdk_core_test --> junit
    com_telenav_tdk_serialization_jersey_json --> com_telenav_tdk_serialization_json
    com_telenav_tdk_serialization_json --> gson
    com_telenav_tdk_serialization_kryo --> kryo
    com_telenav_tdk_serialization_kryo --> kryo_serializers
    com_telenav_tdk_service_client --> com_telenav_tdk_core_network_http
    com_telenav_tdk_service_client --> jersey_client
    com_telenav_tdk_service_client --> jersey_hk2
    com_telenav_tdk_service_client --> jersey_media_json_jackson
    com_telenav_tdk_service_registry --> com_telenav_tdk_core_application
    com_telenav_tdk_service_registry --> com_telenav_tdk_core_network_core
    com_telenav_tdk_service_registry --> com_telenav_tdk_serialization_jersey_json
    com_telenav_tdk_service_server --> com_telenav_tdk_service_client
    com_telenav_tdk_service_server --> com_telenav_tdk_service_registry
    com_telenav_tdk_service_server --> com_telenav_tdk_web_jersey
    com_telenav_tdk_service_server --> com_telenav_tdk_web_jetty
    com_telenav_tdk_service_server --> com_telenav_tdk_web_swagger
    com_telenav_tdk_service_server --> com_telenav_tdk_web_wicket
    com_telenav_tdk_service_server --> jdk_serializable_functional
    com_telenav_tdk_service_server --> wicket_extensions
    com_telenav_tdk_service_server --> wicket_jquery_ui
    com_telenav_tdk_service_server --> wicket_jquery_ui_core
    com_telenav_tdk_web_jersey --> jersey_container_servlet
    com_telenav_tdk_web_jetty --> com_telenav_tdk_core_kernel
    com_telenav_tdk_web_jetty --> jetty_server
    com_telenav_tdk_web_jetty --> jetty_webapp
    com_telenav_tdk_web_swagger --> classgraph
    com_telenav_tdk_web_swagger --> com_telenav_tdk_core_resource
    com_telenav_tdk_web_swagger --> swagger_annotations
    com_telenav_tdk_web_swagger --> swagger_core
    com_telenav_tdk_web_swagger --> swagger_jaxrs2
    com_telenav_tdk_web_swagger --> swagger_models
    com_telenav_tdk_web_swagger --> swagger_ui
    com_telenav_tdk_web_wicket --> wicket_core
    com_telenav_tdk_web_wicket --> wicket_util
    hk2_locator --> aopalliance_repackaged
    hk2_locator --> hk2_api
    hk2_locator --> hk2_utils
    httpclient --> commons_codec
    httpclient --> commons_logging
    httpclient --> httpcore
    jackson_databind --> jackson_core
    jackson_dataformat_yaml --> snakeyaml
    jackson_jaxrs_json_provider --> jackson_jaxrs_base
    jackson_module_jaxb_annotations --> jakarta_activation_api
    jersey_client --> jakarta_inject
    jersey_client --> jakarta_ws_rs_api
    jersey_client --> jersey_common
    jersey_common --> jakarta_annotation_api
    jersey_common --> osgi_resource_locator
    jersey_container_servlet --> jersey_container_servlet_core
    jersey_container_servlet --> jersey_server
    jersey_hk2 --> hk2_locator
    jersey_hk2 --> javassist
    jersey_media_json_jackson --> jackson_annotations
    jersey_media_json_jackson --> jackson_databind
    jersey_media_json_jackson --> jackson_module_jaxb_annotations
    jersey_media_json_jackson --> jersey_entity_filtering
    jetty_http --> jetty_util
    jetty_server --> javax_servlet_api
    jetty_server --> jetty_http
    jetty_server --> jetty_io
    jetty_servlet --> jetty_security
    jetty_servlet --> jetty_util_ajax
    jetty_webapp --> jetty_servlet
    jetty_webapp --> jetty_xml
    junit --> hamcrest_core
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    swagger_core --> commons_lang3
    swagger_core --> jackson_dataformat_yaml
    swagger_core --> jackson_datatype_jsr310
    swagger_core --> jakarta_validation_api
    swagger_core --> jakarta_xml_bind_api
    swagger_jaxrs2 --> jackson_jaxrs_json_provider
    swagger_jaxrs2 --> swagger_integration
    wicket_core --> openjson
    wicket_core --> wicket_request
    wicket_extensions --> slf4j_api
    wicket_util --> commons_collections4
    wicket_util --> commons_fileupload
    wicket_util --> commons_io
    
@enduml
