@startuml

    !include ../lexakai/lexakai.theme
    
    title "kivakit-service-server"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact jackson_core
    artifact jackson_databind
    artifact jackson_dataformat_yaml
    artifact jackson_datatype_jsr310
    artifact jackson_jaxrs_base
    artifact jackson_jaxrs_json_provider
    artifact jackson_module_jaxb_annotations
    artifact openjson
    artifact gson
    artifact wicket_jquery_ui_core
    artifact wicket_jquery_ui
    artifact kivakit_build_metadata
    artifact kivakit_core_application
    artifact kivakit_core_collections
    artifact kivakit_core_commandline
    artifact kivakit_core_configuration
    artifact kivakit_core_kernel
    artifact kivakit_core_network_core
    artifact kivakit_core_network_http
    artifact kivakit_core_resource
    artifact kivakit_core_security
    artifact kivakit_core_serialization_core
    artifact kivakit_core_serialization_jersey_json
    artifact kivakit_core_serialization_json
    artifact kivakit_core_serialization_kryo
    artifact kivakit_core_test
    artifact kivakit_service_client
    artifact kivakit_service_registry
    artifact kivakit_service_server
    artifact kivakit_web_jersey
    artifact kivakit_web_jetty
    artifact kivakit_web_swagger
    artifact kivakit_web_wicket
    artifact lexakai_annotations
    artifact commons_codec
    artifact commons_fileupload
    artifact commons_io
    artifact commons_logging
    artifact kryo_serializers
    artifact classgraph
    artifact swagger_annotations
    artifact swagger_core
    artifact swagger_integration
    artifact swagger_jaxrs2
    artifact swagger_models
    artifact jakarta_activation_api
    artifact jakarta_annotation_api
    artifact jakarta_validation_api
    artifact jakarta_ws_rs_api
    artifact jakarta_xml_bind_api
    artifact javax_servlet_api
    artifact junit
    artifact commons_collections4
    artifact commons_lang3
    artifact httpclient
    artifact httpcore
    artifact wicket_core
    artifact wicket_extensions
    artifact wicket_request
    artifact wicket_util
    artifact jdk_serializable_functional
    artifact jetty_http
    artifact jetty_io
    artifact jetty_security
    artifact jetty_server
    artifact jetty_servlet
    artifact jetty_util_ajax
    artifact jetty_util
    artifact jetty_webapp
    artifact jetty_xml
    artifact aopalliance_repackaged
    artifact jakarta_inject
    artifact hk2_api
    artifact hk2_locator
    artifact hk2_utils
    artifact osgi_resource_locator
    artifact jersey_container_servlet_core
    artifact jersey_container_servlet
    artifact jersey_client
    artifact jersey_common
    artifact jersey_server
    artifact jersey_entity_filtering
    artifact jersey_hk2
    artifact jersey_media_json_jackson
    artifact hamcrest_core
    artifact javassist
    artifact annotations
    artifact objenesis
    artifact asm
    artifact slf4j_api
    artifact swagger_ui
    artifact snakeyaml
    hk2_locator --> aopalliance_repackaged
    hk2_locator --> hk2_api
    hk2_locator --> hk2_utils
    httpclient --> commons_codec
    httpclient --> commons_logging
    httpclient --> httpcore
    jackson_databind --> jackson_core
    jackson_dataformat_yaml --> snakeyaml
    jackson_jaxrs_json_provider --> jackson_jaxrs_base
    jackson_module_jaxb_annotations --> jakarta_activation_api
    jersey_client --> jakarta_inject
    jersey_client --> jakarta_ws_rs_api
    jersey_client --> jersey_common
    jersey_common --> jakarta_annotation_api
    jersey_common --> osgi_resource_locator
    jersey_container_servlet --> jersey_container_servlet_core
    jersey_container_servlet --> jersey_server
    jersey_hk2 --> hk2_locator
    jersey_hk2 --> javassist
    jersey_media_json_jackson --> jackson_annotations
    jersey_media_json_jackson --> jackson_databind
    jersey_media_json_jackson --> jackson_module_jaxb_annotations
    jersey_media_json_jackson --> jersey_entity_filtering
    jetty_http --> jetty_util
    jetty_server --> javax_servlet_api
    jetty_server --> jetty_http
    jetty_server --> jetty_io
    jetty_servlet --> jetty_security
    jetty_servlet --> jetty_util_ajax
    jetty_webapp --> jetty_servlet
    jetty_webapp --> jetty_xml
    junit --> hamcrest_core
    kivakit_core_application --> kivakit_core_commandline
    kivakit_core_application --> kivakit_core_configuration
    kivakit_core_collections --> kivakit_core_serialization_kryo
    kivakit_core_commandline --> kivakit_core_kernel
    kivakit_core_kernel --> annotations
    kivakit_core_kernel --> junit
    kivakit_core_kernel --> kivakit_build_metadata
    kivakit_core_kernel --> lexakai_annotations
    kivakit_core_network_core --> kivakit_core_security
    kivakit_core_network_http --> httpclient
    kivakit_core_resource --> kivakit_core_collections
    kivakit_core_resource --> kivakit_core_serialization_core
    kivakit_core_security --> kivakit_core_test
    kivakit_core_serialization_jersey_json --> kivakit_core_serialization_json
    kivakit_core_serialization_json --> gson
    kivakit_core_serialization_kryo --> kryo
    kivakit_core_serialization_kryo --> kryo_serializers
    kivakit_service_client --> jersey_client
    kivakit_service_client --> jersey_hk2
    kivakit_service_client --> jersey_media_json_jackson
    kivakit_service_client --> kivakit_core_network_http
    kivakit_service_registry --> kivakit_core_application
    kivakit_service_registry --> kivakit_core_network_core
    kivakit_service_registry --> kivakit_core_serialization_jersey_json
    kivakit_service_server --> jdk_serializable_functional
    kivakit_service_server --> kivakit_service_client
    kivakit_service_server --> kivakit_service_registry
    kivakit_service_server --> kivakit_web_jersey
    kivakit_service_server --> kivakit_web_jetty
    kivakit_service_server --> kivakit_web_swagger
    kivakit_service_server --> kivakit_web_wicket
    kivakit_service_server --> wicket_extensions
    kivakit_service_server --> wicket_jquery_ui
    kivakit_service_server --> wicket_jquery_ui_core
    kivakit_web_jersey --> jersey_container_servlet
    kivakit_web_jetty --> jetty_server
    kivakit_web_jetty --> jetty_webapp
    kivakit_web_swagger --> classgraph
    kivakit_web_swagger --> kivakit_core_resource
    kivakit_web_swagger --> swagger_annotations
    kivakit_web_swagger --> swagger_core
    kivakit_web_swagger --> swagger_jaxrs2
    kivakit_web_swagger --> swagger_models
    kivakit_web_swagger --> swagger_ui
    kivakit_web_wicket --> wicket_core
    kivakit_web_wicket --> wicket_util
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    swagger_core --> commons_lang3
    swagger_core --> jackson_dataformat_yaml
    swagger_core --> jackson_datatype_jsr310
    swagger_core --> jakarta_validation_api
    swagger_core --> jakarta_xml_bind_api
    swagger_jaxrs2 --> jackson_jaxrs_json_provider
    swagger_jaxrs2 --> swagger_integration
    wicket_core --> openjson
    wicket_core --> wicket_request
    wicket_extensions --> slf4j_api
    wicket_util --> commons_collections4
    wicket_util --> commons_fileupload
    wicket_util --> commons_io
    
@enduml
