@startuml

    !include ../lexakai/lexakai.theme
    
    title "Service Registry Server"
    
    Server <|-- ServiceRegistryServer
    ServiceRegistryServer --> ServiceRegistry : "creates"
    ServiceRegistryServer --> ServiceRegistry : "searches"
    ServiceRegistryServer --> ServiceRegistry : "updates"
    ServiceRegistryServer --> ServiceRegistryStore : "persists to"
    note right of ServiceRegistryServer
        For REST API details, refer to Swagger documentation provided by this server
    endnote
    class ServiceRegistryServer
    {
        --(constructors)--
        #ServiceRegistryServer()
        --
        +void main(String[] arguments)
        +Scope.Type scope()
        --(checks)--
        +boolean isLocal()
        --(network)--
        +boolean isNetwork()
        +int port()
        --(service)--
        +ServiceRegistryServer get()
        +ServiceRegistry registry()
    }
    
@enduml

