@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.network.core.project"
    
    Project <|-- CoreNetworkCoreProject
    class CoreNetworkCoreProject
    {
        --(constructors)--
        #CoreNetworkCoreProject()
        --(network)--
        +CoreNetworkCoreProject get()
    }
    
@enduml

