@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.http.secure"
    
    DefaultHttpClient <|-- InvalidCertificateTrustingHttpClient
    class InvalidCertificateTrustingHttpClient
    {
        --(constructors)--
        +InvalidCertificateTrustingHttpClient()
    }
    
    HttpGetResource <|-- SecureHttpGetResource
    class SecureHttpGetResource
    {
        --(constructors)--
        +SecureHttpGetResource(SecureHttpNetworkLocation, NetworkAccessConstraints)
        --
        +void ignoreInvalidCertificates(boolean ignore)
    }
    
    HttpNetworkLocation <|-- SecureHttpNetworkLocation
    SecureHttpNetworkLocation --> SecureHttpGetResource : "creates"
    SecureHttpNetworkLocation --> SecureHttpPostResource : "creates"
    class SecureHttpNetworkLocation
    {
        --(constructors)--
        +SecureHttpNetworkLocation(NetworkPath)
    }
    
    HttpPostResource <|-- SecureHttpPostResource
    class SecureHttpPostResource
    {
        --(constructors)--
        +SecureHttpPostResource(NetworkLocation, NetworkAccessConstraints)
        --
        +void ignoreInvalidCertificates(boolean ignore)
    }
    
@enduml

