@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.http.project"
    
    Project <|-- CoreNetworkHttpProject
    class CoreNetworkHttpProject
    {
        --(constructors)--
        #CoreNetworkHttpProject()
        --(network)--
        +CoreNetworkHttpProject get()
    }
    
@enduml

