@startuml

    !include ../lexakai.theme
    
    title "com.telenav.kivakit.data.formats.library.xml.project"
    
    Project <|-- DataFormatsXmlProject
    class DataFormatsXmlProject
    {
        --(constructors)--
        #DataFormatsXmlProject()
        --
        +DataFormatsXmlProject get()
    }
    
@enduml

