@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.logs.email.project"
    
    Project <|-- LogsEmailProject
    class LogsEmailProject
    {
        --(constructors)--
        #LogsEmailProject()
        --(network)--
        +LogsEmailProject get()
    }
    
@enduml

