@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.logs.email"
    
    abstract BaseTextLog
    
    BaseTextLog <|-- EmailLog
    EmailLog o-- EmailSender
    EmailLog "1" o-- "*" EmailAddress : "to"
    EmailLog o-- EmailAddress : "from"
    class EmailLog
    {
    }
    
@enduml

