@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.progress"
    
    interface ProgressListener
    {
        --
        +void at(Percent at)
    }
    
    interface Resettable
    Resettable <|-- ProgressReporter
    ProgressReporter --> ProgressListener : "reports progress to"
    interface ProgressReporter
    {
        --
        +ProgressReporter phase(String phase)
        +ProgressReporter steps(Count steps)
        --(checks)--
        +boolean isIndefinite()
        --(collection)--
        +Count steps()
        --(iteration)--
        +void next()
        +void next(Count steps)
        +void next(int steps)
        --(lifecycle)--
        +void end()
        +void end(String label)
        +ProgressReporter start()
        +ProgressReporter start(String label)
        --(messaging)--
        +ProgressReporter listener(ProgressListener)
    }
    
@enduml

