@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel"
    
    Project <|-- KivaKit
    class KivaKit
    {
        --(constructors)--
        #KivaKit()
        --
        +KivaKit get()
        --(filesystem)--
        +Path cacheFolderPath()
        +Path homeFolderPath()
    }
    
@enduml

