@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.threading.batcher"
    
    abstract BaseRepeater
    
    interface Addable
    
    ArrayList <|-- Batcher.Batch
    class Batcher.Batch
    {
    }
    
    Addable <|-- Batcher.BatchAdder
    class Batcher.BatchAdder
    {
    }
    
    BaseRepeater <|-- Batcher
    abstract class Batcher<Element>
    {
        --(constructors)--
        #Batcher(String, Maximum, Count)
        --
        +BatchAdder adder()
        #void onBatch(Batch)
        --(lifecycle)--
        +void start(Count workers)
        +void stop()
    }
    
    BaseRepeater <|-- BatcherTest
    class BatcherTest
    {
        --
        +void testRandom()
        --(collection)--
        +void testEmptyFlush()
        --(lifecycle)--
        +void testStop()
    }
    
    Batcher <|-- BatcherTest.TestBatcher
    class BatcherTest.TestBatcher
    {
        --(constructors)--
        +TestBatcher()
    }
    
@enduml

