@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.interfaces.messaging"
    
    Receiver --> Transmittable : "receives"
    interface Receiver<T>
    {
        --(messaging)--
        +void receive(T value)
    }
    
    interface Transmittable
    {
    }
    
    Transmitter --> Transmittable : "transmits"
    interface Transmitter<T>
    {
        --(messaging)--
        +void transmit(T value)
    }
    
@enduml

