@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.interfaces.string"
    
    interface Source<String>
    Source <|-- StringSource
    interface StringSource
    {
        --
        +String string()
    }
    
@enduml

