@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.values.name"
    
    interface Named
    
    Named <|-- Name
    class Name
    {
        --(constructors)--
        #Name()
        +Name(String)
        --
        +String of(Object)
        +String synthetic(Object)
        --(naming)--
        +Name lowerCase()
    }
    
@enduml

