@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.threading.latches"
    
    CompletionLatch --> WakeState : "waits until"
    class CompletionLatch
    {
        --(constructors)--
        +CompletionLatch()
        +CompletionLatch(Count)
        --(lifecycle)--
        +void completed()
        +boolean hasCompleted()
        +void reset()
        --(thread)--
        +WakeState waitForCompletion()
        +WakeState waitForCompletion(Duration)
    }
    
    class InitializationLatch
    {
        --
        +void ready()
        --(checks)--
        +boolean isReady()
        --(lifecycle)--
        +void reset()
        --(thread)--
        +boolean await(Duration)
    }
    
@enduml

