@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.reflection.property.filters.field"
    
    KivaKitProperties <|-- AllFields
    class AllFields
    {
        --(constructors)--
        +AllFields(Set<Include>)
    }
    
    AllFields <|-- NamedField
    class NamedField
    {
        --(constructors)--
        +NamedField(String)
    }
    
@enduml

