@startuml

    !include lexakai.theme
    
    title "Interfaces - Model"
    
    interface Quantizable
    Quantizable <|-- Identifiable
    interface Identifiable
    {
        --(identity)--
        +long identifier()
    }
    
    interface Initializer<Model>
    {
        --
        +Initializer<T> nullInitializer()
        --(lifecycle)--
        +void initialize(Model value)
    }
    
    interface ModelListener<Model>
    {
        --
        +void modelChanged(Model)
    }
    
    interface Watchable<Value>
    {
        --
        +Value observe()
    }
    
@enduml

