@startuml

    !include lexakai.theme
    
    title "Interfaces - String"
    
    AsString --> StringFormat : "formats with"
    interface AsString
    {
        --(conversion)--
        +String asString(StringFormat)
        +String asString()
    }
    
    class StringFormat
    {
        --(constructors)--
        +StringFormat(String)
        --
        +StringFormat of(String identifier)
        --(checks)--
        +boolean isHtml()
        +boolean isText()
    }
    
    interface Source<String>
    Source <|-- StringSource
    interface StringSource
    {
        --
        +String string()
    }
    
@enduml

