@startuml

    !include lexakai.theme
    
    title "Interfaces - Persistence"
    
    interface Loadable
    {
        --(read)--
        +void load()
    }
    
    interface Unloadable
    {
        --
        +void unload()
    }
    
@enduml

