@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.compression.codecs.huffman.character"
    
    abstract BaseStringConverter
    
    interface CharacterCodec
    
    class CharacterFrequencies
    {
        --(collection)--
        +Count escaped(Maximum occurrences)
        --(primitive)--
        +CharacterFrequencies add(String)
        +CountMap<Character> frequencies()
        +Symbols<Character> symbols(Minimum occurrences)
        +Symbols<Character> symbols()
    }
    
    BaseStringConverter <|-- HuffmanCharacterCodec.Converter
    class HuffmanCharacterCodec.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    CharacterCodec <|-- HuffmanCharacterCodec
    class HuffmanCharacterCodec
    {
        --(constructors)--
        #HuffmanCharacterCodec()
        --(collection)--
        +PropertyMap asProperties()
        --(primitive)--
        +HuffmanCharacterCodec from(Symbols<Character>, Maximum bits)
        +HuffmanCharacterCodec from(PropertyMap frequencies, Character escape)
        +HuffmanCharacterCodec from(Symbols<Character>)
    }
    
@enduml

