@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.compression.project"
    
    KryoTypes <|-- DataCompressionKryoTypes
    class DataCompressionKryoTypes
    {
        --(constructors)--
        +DataCompressionKryoTypes()
    }
    
    Project <|-- DataCompressionProject
    class DataCompressionProject
    {
        --(constructors)--
        #DataCompressionProject()
        --
        +DataCompressionProject get()
    }
    
    KryoUnitTest <|-- DataCompressionUnitTest
    class DataCompressionUnitTest
    {
        --
        #Symbols<String> fixedSymbolSet()
        #Symbols<String> randomStringSymbols(int minimum, int maximum, int minimumLength, int maximumLength)
        #void test(Codec<String>, List<String> symbols)
        #void testDecode(Codec<String>, ByteList data, List<String> expected)
        --(collection)--
        #PropertyMap properties(String name)
        --(primitive)--
        #ByteList encode(Codec<String>, List<String> values)
        #Symbols<Character> randomCharacterSymbols(int minimum, int maximum)
    }
    
@enduml

