@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.compression"
    
    interface Codec<Symbol>
    {
        --
        +void decode(ByteList input, SymbolConsumer<Symbol>)
        --(checks)--
        +boolean canEncode(Symbol)
        --(primitive)--
        +ByteList encode(ByteList output, SymbolProducer<Symbol>)
    }
    
    enum SymbolConsumer.Directive
    {
        CONTINUE
        STOP
    }
    
    interface SymbolConsumer<Symbol>
    {
        --
        +Directive onEscape(ByteList input)
        --(iteration)--
        +Directive next(int ordinal, Symbol)
    }
    
    interface SymbolProducer<Symbol>
    {
        --
        +Symbol get(int ordinal)
        +void onEscape(ByteList output, Symbol)
        +SymbolProducer<Symbol> singleton(Symbol)
        --(collection)--
        +SymbolProducer<Symbol> fromList(List<Symbol> symbols)
        +int size()
        --(lifecycle)--
        +void reset()
    }
    
@enduml

