@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.compression.codecs.huffman.string"
    
    abstract BaseStringConverter
    
    interface StringCodec
    
    BaseStringConverter <|-- HuffmanStringCodec.Converter
    class HuffmanStringCodec.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    StringCodec <|-- HuffmanStringCodec
    class HuffmanStringCodec
    {
        --(constructors)--
        #HuffmanStringCodec()
        --
        +HuffmanStringCodec from(Symbols<String>, Maximum bits)
        +HuffmanStringCodec from(Symbols<String>)
        +HuffmanStringCodec from(PropertyMap frequencies)
        --(collection)--
        +PropertyMap asProperties()
    }
    
    class StringFrequencies
    {
        --(constructors)--
        +StringFrequencies(Count, Maximum)
        --
        +Symbols<String> symbols(Minimum occurrences)
        +Symbols<String> symbols()
        +StringFrequencies top(Count)
        --(collection)--
        +StringFrequencies add(String)
        +CountMap<String> frequencies()
    }
    
@enduml

