@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.data.compression.codecs"
    
    interface StringCodec
    StringCodec <|-- CharacterCodec
    interface CharacterCodec
    {
    }
    
    interface Codec<String>
    Codec <|-- StringCodec
    interface StringCodec
    {
        --
        +void train(Iterable<String> strings)
        +void train(String)
    }
    
    interface StringCodec
    StringCodec <|-- StringListCodec
    interface StringListCodec
    {
    }
    
@enduml

