@startuml

    !include lexakai.theme
    
    title "Security"
    
    interface Password
    
    PlainTextPassword <|-- DigestPassword
    class DigestPassword
    {
        --(constructors)--
        +DigestPassword(String)
    }
    
    interface Matcher
    Matcher <|-- Password
    interface Password
    {
    }
    
    Password <|-- PlainTextPassword
    class PlainTextPassword
    {
        --(constructors)--
        #PlainTextPassword(String)
        --(parsing)--
        +PlainTextPassword parse(String password)
    }
    
    Name <|-- UserName
    class UserName
    {
        --(constructors)--
        #UserName(String)
        --(naming)--
        +UserName parse(String name)
    }
    
@enduml

