@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.resource.writing"
    
    abstract BaseReadableResource
    
    interface WritableResource
    
    BaseReadableResource <|-- BaseWritableResource
    WritableResource <|-- BaseWritableResource
    abstract class BaseWritableResource
    {
        --(constructors)--
        #BaseWritableResource()
        #BaseWritableResource(BaseWritableResource)
        #BaseWritableResource(ResourcePath)
        --
        +void print(String text)
        +void println(String text)
        --(filesystem)--
        +void copyFrom(Resource, CopyMode, ProgressReporter)
        +boolean delete()
        --(write)--
        +void save(InputStream, ProgressReporter)
    }
    
    class ResourceWriter
    {
        --(constructors)--
        +ResourceWriter(WritableResource)
        +ResourceWriter(WritableResource, Charset)
        --
        +Charset charset()
        --(write)--
        +PrintWriter printWriter()
        +void save(String)
        +Writer textWriter()
    }
    
@enduml

