@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.ftp.project"
    
    Project <|-- CoreNetworkFtpProject
    class CoreNetworkFtpProject
    {
        --(constructors)--
        #CoreNetworkFtpProject()
        --(network)--
        +CoreNetworkFtpProject get()
    }
    
@enduml

