@startuml

    !include ../lexakai.theme
    
    title "com.telenav.kivakit.data.formats.library.text.project"
    
    Project <|-- DataFormatsTextProject
    class DataFormatsTextProject
    {
        --(constructors)--
        #DataFormatsTextProject()
        --
        +DataFormatsTextProject get()
    }
    
@enduml

