@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.core.project"
    
    Project <|-- CoreNetworkCoreProject
    class CoreNetworkCoreProject
    {
        --(constructors)--
        #CoreNetworkCoreProject()
        --(network)--
        +CoreNetworkCoreProject get()
    }
    
@enduml

