@startuml

    !include ../lexakai/lexakai.theme
    
    title "Network Locations"
    
    abstract BaseReadableResource
    
    interface NetworkResource
    interface AsString
    interface Comparable
    interface Validatable
    
    BaseReadableResource <|-- BaseNetworkResource
    NetworkResource <|-- BaseNetworkResource
    abstract class BaseNetworkResource
    {
        --(constructors)--
        #BaseNetworkResource(BaseReadableResource)
        #BaseNetworkResource(NetworkLocation)
        --(network)--
        +URI asUri()
        +URL asUrl()
    }
    
    Validatable <|-- NetworkAccessConstraints
    NetworkAccessConstraints o-- Duration
    NetworkAccessConstraints o-- UserName
    NetworkAccessConstraints o-- Password
    class NetworkAccessConstraints
    {
        --
        +void password(Password)
        +Password password()
        --(naming)--
        +void userName(UserName)
        +UserName userName()
        --(network)--
        +Duration timeout()
        +NetworkAccessConstraints timeout(Duration timeout)
    }
    
    AsString <|-- NetworkLocation
    Comparable <|-- NetworkLocation
    NetworkLocation o-- Port
    NetworkLocation o-- NetworkPath
    NetworkLocation o-- NetworkAccessConstraints
    NetworkLocation o-- QueryParameters : "optional"
    class NetworkLocation
    {
        --(constructors)--
        +NetworkLocation(NetworkLocation)
        +NetworkLocation(NetworkPath)
        --
        +void constraints(NetworkAccessConstraints)
        +void reference(String fragment)
        +String reference()
        --(checks)--
        +boolean isChildOf(NetworkLocation that)
        --(network)--
        +URI asUri()
        +URL asUrl()
        +NetworkAccessConstraints constraints()
        +Host host()
        +NetworkPath networkPath()
        +Port port()
        +Protocol protocol()
        +NetworkLocation withPath(NetworkPath)
        +NetworkLocation withQueryParameters(QueryParameters)
        --(search)--
        +QueryParameters queryParameters()
        +void queryParameters(QueryParameters)
    }
    
    FilePath <|-- NetworkPath
    class NetworkPath
    {
        --(constructors)--
        #NetworkPath(NetworkPath)
        #NetworkPath(Port, String, List<String>)
        #NetworkPath(Port, StringPath)
        --(network)--
        +URI asUri()
        +NetworkPath networkPath(URI)
        +NetworkPath networkPath(Port, String path)
        +NetworkPath parseNetworkPath(String path)
        +Port port()
    }
    
    interface Resource
    Resource <|-- NetworkResource
    NetworkResource --> NetworkLocation : "located at"
    interface NetworkResource
    {
        --(network)--
        +NetworkLocation location()
    }
    
    class QueryParameters
    {
        --(constructors)--
        #QueryParameters(String)
        +QueryParameters(VariableMap<String>)
        --(collection)--
        +VariableMap<String> asMap()
        +boolean isEmpty()
        --(search)--
        +QueryParameters parse(String)
    }
    
@enduml

