@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.jersey.project"
    
    Project <|-- WebJerseyProject
    class WebJerseyProject
    {
        --(constructors)--
        #WebJerseyProject()
        --
        +WebJerseyProject get()
    }
    
@enduml

