@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.resource.spi"
    
    ResourceFolderResolver --> ResourceIdentifier : "parses"
    ResourceFolderResolver --> ResourceFolder : "creates"
    interface ResourceFolderResolver
    {
        --(filesystem)--
        +ResourceFolder resolve(ResourceFolderIdentifier)
        --(filtering)--
        +boolean accepts(ResourceFolderIdentifier)
    }
    
    ResourceFolderResolverServiceLoader "1" o-- "*" ResourceFolderResolver
    class ResourceFolderResolverServiceLoader
    {
        --(filesystem)--
        +ResourceFolder resolve(ResourceFolderIdentifier)
    }
    
    ResourceResolver --> ResourceFolderIdentifier : "parses"
    ResourceResolver --> Resource : "creates"
    interface ResourceResolver
    {
        --
        +Resource resolve(ResourceIdentifier)
        --(filtering)--
        +boolean accepts(ResourceIdentifier)
    }
    
    ResourceResolverServiceLoader "1" o-- "*" ResourceResolver
    class ResourceResolverServiceLoader
    {
        --
        +Resource resolve(ResourceIdentifier)
    }
    
@enduml

