@startuml

    !include ../lexakai.theme
    
    title "com.telenav.kivakit.core.resource.store"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- BinaryObjectStore
    abstract class BinaryObjectStore<Type>
    {
        --(constructors)--
        #BinaryObjectStore(Listener, Resource)
        --(read)--
        +Type read()
        #Type onRead()
        #boolean readBit()
        #int readInteger(int bits)
        #long readLong(int bits)
        --(write)--
        +void write(Type value)
        #void onWrite(Type value)
        #void write(int value, int bits)
        #void write(long value, int bits)
        #void write(boolean bit)
    }
    
@enduml

