@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.filesystem.local"
    
    abstract BaseWritableResource
    
    interface FileSystemService
    interface FileService
    interface DiskService
    interface FolderService
    
    DiskService <|-- LocalDisk
    -class LocalDisk
    {
        --(constructors)--
        +LocalDisk(LocalFolder)
    }
    
    BaseWritableResource <|-- LocalFile
    FileService <|-- LocalFile
    -class LocalFile
    {
        --(constructors)--
        +LocalFile(FilePath)
        +LocalFile(LocalFile)
        +LocalFile(LocalFolder, String)
        +LocalFile(String)
        +LocalFile(java.io.File)
        --(filesystem)--
        +boolean isFile(FilePath)
    }
    
    FileSystemService <|-- LocalFileSystemService
    LocalFileSystemService --> LocalDisk : "creates"
    LocalFileSystemService --> LocalFile : "creates"
    LocalFileSystemService --> LocalFolder : "creates"
    -class LocalFileSystemService
    {
    }
    
    FolderService <|-- LocalFolder
    -class LocalFolder
    {
        --(constructors)--
        +LocalFolder(FilePath)
        +LocalFolder(LocalFolder)
        +LocalFolder(String)
        +LocalFolder(URI)
        +LocalFolder(URL)
        +LocalFolder(java.io.File)
        --(filesystem)--
        +LocalFolder asAbsolute()
        +LocalFolder ensureExists()
        +LocalFile file(FilePath)
        +LocalFile file(String name)
        +LocalFolder folder(String child)
        +LocalFolder folder(LocalFolder child)
        +LocalFolder home()
        --(network)--
        +URI asUri()
        +URL asUrl()
    }
    
@enduml

