@startuml

    !include ../lexakai/lexakai.theme
    
    title "Resources"
    
    abstract BaseRepeater
    abstract BaseReadableResource
    
    interface WritableResource
    interface Resource
    
    BaseRepeater <|-- BaseReadableResource
    Resource <|-- BaseReadableResource
    abstract class BaseReadableResource
    {
        --(constructors)--
        #BaseReadableResource()
        #BaseReadableResource(BaseReadableResource)
        #BaseReadableResource(ResourcePath)
        --
        +BaseReadableResource codec(Codec)
        #void charset(Charset)
        --(filesystem)--
        +void safeCopyTo(Folder destination, CopyMode, ProgressReporter)
    }
    
    BaseReadableResource <|-- BaseWritableResource
    WritableResource <|-- BaseWritableResource
    abstract class BaseWritableResource
    {
        --(constructors)--
        #BaseWritableResource()
        #BaseWritableResource(BaseWritableResource)
        #BaseWritableResource(ResourcePath)
        --
        +void print(String text)
        +void println(String text)
        --(filesystem)--
        +void copyFrom(Resource, CopyMode, ProgressReporter)
        +boolean delete()
        --(write)--
        +void save(InputStream, ProgressReporter)
    }
    
    interface Readable
    Readable <|-- ReadableResource
    ReadableResource --> ResourceReader : "provides"
    interface ReadableResource
    {
        --
        +Charset charset()
        +Resource resource()
        --(conversion)--
        +StringResource asStringResource()
        --(filesystem)--
        +void copyTo(WritableResource destination, CopyMode, ProgressReporter)
        --(read)--
        +ResourceReader reader(ProgressReporter)
        +ResourceReader reader(ProgressReporter, Charset)
        +ResourceReader reader()
    }
    
    interface ByteSized
    interface ModificationTimestamped
    interface ReadableResource
    interface Repeater
    interface ResourcePathed
    interface Resourceful
    ResourcePathed <|-- Resource
    ModificationTimestamped <|-- Resource
    ByteSized <|-- Resource
    ReadableResource <|-- Resource
    Repeater <|-- Resource
    Resourceful <|-- Resource
    Resource --> Codec : "uses"
    interface Resource
    {
        --
        +Codec codec()
        +void dematerialize()
        +Resource resolve(ResourceIdentifier)
        +Resource resolve(String identifier)
        --(checks)--
        +boolean isEmpty()
        +boolean isLocal()
        +boolean isMaterializable()
        +boolean isPackaged()
        +boolean isRemote()
        +boolean isSame(Resource that)
        --(command line parsing)--
        +ArgumentParser.Builder<Resource> resource(Listener, String description)
        +SwitchParser.Builder<Resource> resource(Listener, String name, String description)
        +ArgumentParser.Builder<ResourceList> resourceList(String description, Extension)
        +SwitchParser.Builder<ResourceList> resourceList(String name, String description, Extension)
        +SwitchParser.Builder<ResourcePath> resourcePath(String name, String description)
        --(filesystem)--
        +void ensureExists()
        +boolean exists()
        +void safeCopyTo(File destination, CopyMode, ProgressReporter)
        --(functional)--
        +Resource materialized(ProgressReporter)
        --(identity)--
        +ResourceIdentifier identifier(String identifier)
    }
    
    ArrayList <|-- ResourceList
    ResourceList --> Resource : "contains"
    class ResourceList
    {
        --(constructors)--
        +ResourceList()
        +ResourceList(Extension)
        +ResourceList(Iterable<Resource>)
        --(collection)--
        +Count count()
        +ResourceList matching(Matcher<Resource>)
        +ResourceList matching(Extension)
        +ResourceList relativeTo(Folder)
        +void sortOldestToNewest()
        +Bytes totalSize()
        --(math)--
        +Resource largest()
        +Resource smallest()
    }
    
    StringPath <|-- ResourcePath
    class ResourcePath
    {
        --(constructors)--
        #ResourcePath(List<String>)
        #ResourcePath(ResourcePath)
        #ResourcePath(String, List<String>)
        --(filesystem)--
        +File asFile()
        +FileName fileName()
        --(path)--
        +FilePath asFilePath()
        +ResourcePath normalized()
        +ResourcePath parseResourcePath(String path)
        +ResourcePath parseUnixResourcePath(String path)
        +ResourcePath resourcePath(StringPath)
        +FilePath withExtension(Extension)
    }
    
    ResourcePathed --> ResourcePath : "supplies"
    interface ResourcePathed
    {
        --(filesystem)--
        +FileName baseName()
        +Extension compoundExtension()
        +Extension extension()
        +FileName fileName()
        +boolean hasExtension(Extension)
        --(path)--
        +ResourcePath path()
    }
    
    class ResourceReader
    {
        --(constructors)--
        +ResourceReader(Resource, ProgressReporter, Charset)
        --
        +Set<T> objectSet(Converter<String,T>, ProgressReporter)
        +String string(ProgressReporter)
        --(collection)--
        +Iterable<String> lines(ProgressReporter)
        +Iterable<String> lines()
        +StringList linesAsStringList()
        +StringList linesAsStringList(ProgressReporter)
        +List<T> objectList(Converter<String,T>, ProgressReporter)
        +Iterable<T> objects(Converter<String,T>, ProgressReporter)
        --(primitive)--
        +byte[] bytes()
        --(read)--
        +Reader textReader()
    }
    
    class ResourceWriter
    {
        --(constructors)--
        +ResourceWriter(WritableResource)
        +ResourceWriter(WritableResource, Charset)
        --
        +Charset charset()
        --(write)--
        +PrintWriter printWriter()
        +void save(String)
        +Writer textWriter()
    }
    
    interface Resource
    interface Writable
    Resource <|-- WritableResource
    Writable <|-- WritableResource
    WritableResource --> ResourceWriter : "provides"
    interface WritableResource
    {
        --(write)--
        +PrintWriter printWriter()
        +ResourceWriter writer()
        +ResourceWriter writer(Charset)
    }
    
@enduml

