
@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.logs.file.project.lexakai.diagrams"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramLogsFile
    class DiagramLogsFile
    {
    }
    
@enduml

