@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.logs.file.project"
    
    Project <|-- LogsFileProject
    class LogsFileProject
    {
        --(constructors)--
        #LogsFileProject()
        --(filesystem)--
        +LogsFileProject get()
    }
    
@enduml

