@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.filesystems.hdfs.proxy"
    
    interface HdfsProxy
    
    class HdfsFileSystem
    {
        --(filesystem)--
        +HdfsFileSystem of(FilePath)
    }
    
    Server <|-- HdfsProxyServer
    HdfsProxy <|-- HdfsProxyServer
    HdfsProxyServer --> HdfsFileSystem : "delegates to"
    HdfsProxyServer --> HdfsProxyServerSettings : "configures with"
    class HdfsProxyServer
    {
        --(constructors)--
        +HdfsProxyServer()
        --
        +void main(String[] arguments)
    }
    
    class HdfsProxyServerSettings
    {
        --
        +HdfsProxyServerSettings user(UserGroupInformation)
        --(filesystem)--
        +ResourceFolder configurationFolder()
        +HdfsProxyServerSettings configurationFolder(ResourceFolder configuration)
        --(messaging)--
        +UserGroupInformation user()
    }
    
    class StreamHandle
    {
        --(identity)--
        +Identifier identifier()
        --(messaging)--
        +StreamHandle create()
        +StreamHandle of(long identifier)
    }
    
@enduml

