
@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.filesystems.hdfs.proxy.project.lexakai.diagrams"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramHdfsProxy
    class DiagramHdfsProxy
    {
    }
    
@enduml

