@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.filesystems.hdfs.proxy.converters"
    
    abstract BaseStringConverter
    
    BaseStringConverter <|-- UserGroupInformationConverter
    class UserGroupInformationConverter
    {
        --(constructors)--
        +UserGroupInformationConverter(Listener)
    }
    
@enduml

