@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.swagger.project"
    
    Project <|-- WebSwaggerProject
    class WebSwaggerProject
    {
        --(constructors)--
        #WebSwaggerProject()
        --
        +WebSwaggerProject get()
    }
    
@enduml

