@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.security.authentication.passwords"
    
    interface Password
    
    PlainTextPassword <|-- DigestPassword
    class DigestPassword
    {
        --(constructors)--
        +DigestPassword(String)
    }
    
    Password <|-- PlainTextPassword
    class PlainTextPassword
    {
        --(constructors)--
        +PlainTextPassword(String)
    }
    
@enduml

