@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.security.authentication.passwords"
    
    abstract BaseStringConverter
    
    interface Password
    
    BaseStringConverter <|-- PlainTextPassword.Converter
    class PlainTextPassword.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    PlainTextPassword <|-- DigestPassword
    class DigestPassword
    {
        --(constructors)--
        +DigestPassword(String)
    }
    
    Password <|-- PlainTextPassword
    class PlainTextPassword
    {
        --(constructors)--
        #PlainTextPassword(String)
        --(parsing)--
        +PlainTextPassword parse(String password)
    }
    
@enduml

