@startuml

    !include ../lexakai/lexakai.theme
    
    title "kivakit-core-security"
    
    artifact jackson_annotations
    artifact kivakit_build_metadata
    artifact kivakit_core_kernel
    artifact kivakit_core_security
    artifact kivakit_core_test
    artifact lexakai_annotations
    artifact swagger_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_core_kernel --> annotations
    kivakit_core_kernel --> jackson_annotations
    kivakit_core_kernel --> junit
    kivakit_core_kernel --> kivakit_build_metadata
    kivakit_core_kernel --> lexakai_annotations
    kivakit_core_kernel --> swagger_annotations
    kivakit_core_security --> kivakit_core_test
    kivakit_core_test --> kivakit_core_kernel
    
@enduml
