@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.project.lexakai.annotations"
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramRegistry
    interface DiagramRegistry
    {
    }
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramRest
    interface DiagramRest
    {
    }
    
@enduml

