@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.serialization.serializers"
    
    PrimitiveGsonSerializer <|-- ApplicationIdentifierSerializer
    class ApplicationIdentifierSerializer
    {
        --(constructors)--
        +ApplicationIdentifierSerializer()
    }
    
    PrimitiveGsonSerializer <|-- ProblemSerializer
    class ProblemSerializer
    {
        --(constructors)--
        +ProblemSerializer()
    }
    
    PrimitiveGsonSerializer <|-- ServiceTypeSerializer
    class ServiceTypeSerializer
    {
        --(constructors)--
        +ServiceTypeSerializer()
    }
    
    PrimitiveGsonSerializer <|-- TimeSerializer
    class TimeSerializer
    {
        --(constructors)--
        +TimeSerializer()
    }
    
@enduml

