@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.registries"
    
    abstract BaseServiceRegistry
    abstract BaseRepeater
    
    interface ServiceRegistry
    
    BaseRepeater <|-- BaseServiceRegistry
    ServiceRegistry <|-- BaseServiceRegistry
    -abstract class BaseServiceRegistry
    {
        --(constructors)--
        +BaseServiceRegistry()
        --(service)--
        +ServiceRegistry load()
        +BaseServiceRegistry updater(ServiceRegistryUpdater)
    }
    
    BaseServiceRegistry <|-- LocalServiceRegistry
    -class LocalServiceRegistry
    {
        --(constructors)--
        #LocalServiceRegistry()
        +LocalServiceRegistry(int)
    }
    
    BaseServiceRegistry <|-- NetworkServiceRegistry
    -class NetworkServiceRegistry
    {
    }
    
@enduml

