@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.protocol.discover"
    
    abstract BaseResponse
    abstract BaseRequest
    
    BaseRequest <|-- DiscoverApplicationsRequest
    class DiscoverApplicationsRequest
    {
        --
        +Scope scope()
        --(search)--
        +DiscoverApplicationsRequest scope(Scope)
    }
    
    BaseResponse <|-- DiscoverApplicationsResponse
    class DiscoverApplicationsResponse
    {
        --(identity)--
        +Set<ApplicationIdentifier> applications()
        --(search)--
        +DiscoverApplicationsResponse applications(Set<ApplicationIdentifier> applications)
    }
    
    BaseRequest <|-- DiscoverPortServiceRequest
    class DiscoverPortServiceRequest
    {
        --(network)--
        +DiscoverPortServiceRequest port(Port)
        +Port port()
    }
    
    BaseResponse <|-- DiscoverPortServiceResponse
    class DiscoverPortServiceResponse
    {
        --(service)--
        +Service service()
        +DiscoverPortServiceResponse service(Service)
    }
    
    BaseRequest <|-- DiscoverServicesRequest
    class DiscoverServicesRequest
    {
        --
        +Scope scope()
        --(identity)--
        +ApplicationIdentifier application()
        --(search)--
        +DiscoverServicesRequest application(ApplicationIdentifier)
        +DiscoverServicesRequest scope(Scope)
        +DiscoverServicesRequest serviceType(ServiceType)
        +SearchType type()
        +DiscoverServicesRequest type(SearchType)
        --(service)--
        +ServiceType serviceType()
    }
    
    BaseResponse <|-- DiscoverServicesResponse
    class DiscoverServicesResponse
    {
        --(search)--
        +DiscoverServicesResponse services(Set<Service> services)
        --(service)--
        +Service service()
        +Set<Service> services()
    }
    
    enum DiscoverServicesRequest.SearchType
    {
        ALL_SERVICES
        APPLICATION_SERVICES
        SERVICES_OF_TYPE
    }
    
@enduml

