@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.protocol.renew"
    
    abstract BaseResponse
    abstract BaseRequest
    
    BaseRequest <|-- RenewServiceRequest
    class RenewServiceRequest
    {
        --(constructors)--
        #RenewServiceRequest()
        +RenewServiceRequest(Service)
        --(service)--
        +Service service()
    }
    
    BaseResponse <|-- RenewServiceResponse
    class RenewServiceResponse
    {
        --(service)--
        +RenewServiceResponse service(Service)
        +Service service()
    }
    
@enduml

