@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.store"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- ServiceRegistryStore
    ServiceRegistryStore --> ServiceRegistry : "loads"
    -class ServiceRegistryStore
    {
        --(service)--
        +ServiceRegistry load(Class<? extends ServiceRegistry> type)
        --(write)--
        +void save(ServiceRegistry)
    }
    
@enduml

