@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.service.registry.protocol.register"
    
    abstract BaseResponse
    abstract BaseRequest
    
    BaseRequest <|-- RegisterServiceRequest
    class RegisterServiceRequest
    {
        --(constructors)--
        #RegisterServiceRequest()
        +RegisterServiceRequest(Service)
        --(service)--
        +Service service()
    }
    
    BaseResponse <|-- RegisterServiceResponse
    class RegisterServiceResponse
    {
        --(service)--
        +RegisterServiceResponse service(Service)
        +Service service()
    }
    
@enduml

