@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.service.registry.project"
    
    KryoTypes <|-- ServiceRegistryKryoTypes
    class ServiceRegistryKryoTypes
    {
        --(constructors)--
        +ServiceRegistryKryoTypes()
    }
    
    Project <|-- ServiceRegistryProject
    class ServiceRegistryProject
    {
        --(serialization)--
        +SerializationSessionFactory sessionFactory()
        --(service)--
        +ServiceRegistryProject get()
    }
    
@enduml

