@startuml

    !include ../lexakai.theme
    
    title "com.telenav.tdk.service.registry.serialization"
    
    GsonFactory <|-- ServiceRegistryGsonFactory
    class ServiceRegistryGsonFactory
    {
    }
    
    JerseyGsonSerializer <|-- ServiceRegistryJerseySerializer
    class ServiceRegistryJerseySerializer<T>
    {
        --(constructors)--
        +ServiceRegistryJerseySerializer()
    }
    
@enduml

