@startuml

    !include ../lexakai/lexakai.theme
    
    title "Service Registry REST Protocol"
    
    abstract BaseResponse
    abstract BaseRequest
    
    abstract class BaseRequest
    {
        --(identity)--
        +Version version()
        --(path)--
        +String path()
    }
    
    abstract class BaseResponse<T>
    {
        --
        +void result(Result<T>)
        #void value(T value)
        --(collection)--
        #T value()
        --(conversion)--
        +Result<T> asResult()
        --(identity)--
        +Version version()
        --(messaging)--
        +Problem problem()
        +BaseResponse<T> problem(String message, Object... arguments)
    }
    
    BaseRequest <|-- DiscoverApplicationsRequest
    class DiscoverApplicationsRequest
    {
        --
        +Scope scope()
        --(search)--
        +DiscoverApplicationsRequest scope(Scope)
    }
    
    BaseResponse <|-- DiscoverApplicationsResponse
    class DiscoverApplicationsResponse
    {
        --(identity)--
        +Set<ApplicationIdentifier> applications()
        --(search)--
        +DiscoverApplicationsResponse applications(Set<ApplicationIdentifier> applications)
    }
    
    BaseRequest <|-- DiscoverPortServiceRequest
    class DiscoverPortServiceRequest
    {
        --(network)--
        +DiscoverPortServiceRequest port(Port)
        +Port port()
    }
    
    BaseResponse <|-- DiscoverPortServiceResponse
    class DiscoverPortServiceResponse
    {
        --(service)--
        +Service service()
        +DiscoverPortServiceResponse service(Service)
    }
    
    BaseRequest <|-- DiscoverServicesRequest
    class DiscoverServicesRequest
    {
        --
        +Scope scope()
        --(identity)--
        +ApplicationIdentifier application()
        --(search)--
        +DiscoverServicesRequest application(ApplicationIdentifier)
        +DiscoverServicesRequest scope(Scope)
        +DiscoverServicesRequest serviceType(ServiceType)
        +SearchType type()
        +DiscoverServicesRequest type(SearchType)
        --(service)--
        +ServiceType serviceType()
    }
    
    BaseResponse <|-- DiscoverServicesResponse
    class DiscoverServicesResponse
    {
        --(search)--
        +DiscoverServicesResponse services(Set<Service> services)
        --(service)--
        +Service service()
        +Set<Service> services()
    }
    
    BaseResponse <|-- NetworkRegistryUpdateResponse
    class NetworkRegistryUpdateResponse
    {
        --
        +boolean added()
        --(functional)--
        +NetworkRegistryUpdateResponse added(boolean added)
    }
    
    BaseResponse <|-- RegisterServiceResponse
    class RegisterServiceResponse
    {
        --(service)--
        +RegisterServiceResponse service(Service)
        +Service service()
    }
    
    BaseResponse <|-- RenewServiceResponse
    class RenewServiceResponse
    {
        --(service)--
        +RenewServiceResponse service(Service)
        +Service service()
    }
    
@enduml

