@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.jetty"
    
    abstract BaseRepeater
    
    interface Named
    
    Named <|-- BaseJettyRequestHandler
    abstract class BaseJettyRequestHandler
    {
        --(constructors)--
        +BaseJettyRequestHandler(String)
        --(path)--
        #String path()
        #void path(String path)
    }
    
    BaseRepeater <|-- JettyServer
    class JettyServer
    {
        --(constructors)--
        +JettyServer()
        --
        +void configureLogging()
        --(collection)--
        +JettyServer add(String path, BaseJettyServlet)
        +JettyServer add(String path, BaseJettyResource)
        +JettyServer add(String path, BaseJettyFilter)
        --(lifecycle)--
        +void start()
        --(network)--
        +JettyServer port(int port)
    }
    
    UnitTest <|-- WebUnitTest
    class WebUnitTest
    {
        --(lifecycle)--
        #void startWebServer(int portNumber, FilePath war)
    }
    
@enduml

