@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.jetty.resources"
    
    abstract BaseJettyRequestHandler
    
    BaseJettyRequestHandler <|-- BaseJettyFilter
    abstract class BaseJettyFilter
    {
        --(constructors)--
        +BaseJettyFilter(String)
        --
        +EnumSet<DispatcherType> dispatchers()
        --(filtering)--
        +FilterHolder holder()
    }
    
    BaseJettyRequestHandler <|-- BaseJettyResource
    abstract class BaseJettyResource
    {
        --(constructors)--
        +BaseJettyResource(String)
        --
        +ServletHolder holder()
    }
    
    BaseJettyRequestHandler <|-- BaseJettyServlet
    abstract class BaseJettyServlet
    {
        --(constructors)--
        +BaseJettyServlet(String)
        --
        +ServletHolder holder()
    }
    
@enduml

