@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.jetty.project"
    
    Project <|-- WebJettyProject
    class WebJettyProject
    {
        --(constructors)--
        #WebJettyProject()
        --
        +WebJettyProject get()
    }
    
@enduml

