@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.email.project"
    
    Project <|-- CoreNetworkEmailProject
    class CoreNetworkEmailProject
    {
        --(constructors)--
        #CoreNetworkEmailProject()
        --(network)--
        +CoreNetworkEmailProject get()
    }
    
@enduml

