@startuml

    !include lexakai.theme
    
    title "kivakit-network-ftp"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact jsch
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_kernel
    artifact kivakit_network_core
    artifact kivakit_network_ftp
    artifact kivakit_resource
    artifact kivakit_security
    artifact kivakit_serialization_core
    artifact kivakit_serialization_kryo
    artifact kivakit_test
    artifact lexakai_annotations
    artifact commons_net
    artifact kryo_serializers
    artifact swagger_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    artifact objenesis
    artifact asm
    artifact j2ssh_core
    junit --> hamcrest_core
    kivakit_collections --> kivakit_serialization_kryo
    kivakit_commandline --> kivakit_kernel
    kivakit_kernel --> annotations
    kivakit_kernel --> cactus_build_metadata
    kivakit_kernel --> jackson_annotations
    kivakit_kernel --> junit
    kivakit_kernel --> lexakai_annotations
    kivakit_kernel --> swagger_annotations
    kivakit_network_core --> kivakit_commandline
    kivakit_network_core --> kivakit_security
    kivakit_network_ftp --> commons_net
    kivakit_network_ftp --> j2ssh_core
    kivakit_network_ftp --> jsch
    kivakit_network_ftp --> kivakit_network_core
    kivakit_network_ftp --> kivakit_resource
    kivakit_resource --> kivakit_collections
    kivakit_resource --> kivakit_serialization_core
    kivakit_security --> kivakit_test
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    
@enduml
