@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.wicket.library"
    
    class Components
    {
        --
        +void update(Component, Frequency, Consumer<AjaxRequestTarget> afterUpdate)
    }
    
@enduml

