@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.wicket.components.header"
    
    Panel <|-- HeaderPanel
    class HeaderPanel
    {
        --(constructors)--
        +HeaderPanel(String, Version, String)
    }
    
@enduml

