@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.web.wicket.theme"
    
    class KivaKitTheme
    {
        --
        +CssResourceReference kivakitColors()
        +CssResourceReference kivakitTheme()
    }
    
@enduml

