@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.network.socket.project"
    
    Project <|-- CoreNetworkSocket
    class CoreNetworkSocket
    {
        --(constructors)--
        #CoreNetworkSocket()
        --(network)--
        +CoreNetworkSocket get()
    }
    
@enduml

