
@startuml

    !include ../lexakai.theme

    title "Interface Composition of Components"

    class Multicaster

    abstract class BaseRepeater
    abstract class BaseComponent

    interface Broadcaster
    interface Transceiver
    interface Receiver
    interface Transmitter
    interface NamedObject
    interface Repeater
    interface Listener
    interface Broadcaster
    interface Receiver
    interface Component

    interface SettingsTrait
    interface ProjectTrait
    interface PackageTrait
    interface RegistryTrait
    interface LanguageTrait
    interface SettingsTrait

    interface NamedObject

    interface Mixin
    interface RepeaterMixin
    interface ComponentMixin

    ComponentMixin -r-|> Component
    ComponentMixin -u-|> Mixin
    ComponentMixin -u-|> RepeaterMixin

    BaseComponent -u-|> BaseRepeater
    BaseComponent -u-|> Component

    Listener -u-|> Transceiver

    Repeater -u-|> Listener
    Repeater -u-|> Broadcaster
    Repeater -u-|> Receiver

    RepeaterMixin -u-|> Repeater
    RepeaterMixin -u-|> Mixin

    BaseRepeater -u-|> Multicaster

    Multicaster -u-|> Broadcaster

    Broadcaster -u-|> Transceiver

    Transceiver -u-|> Receiver
    Transceiver -u-|> Transmitter
    Transceiver -u-|> NamedObject

    Component -u-|> Repeater
    Component -d-|> ProjectTrait
    Component -u-|> PackageTrait
    Component -l-|> RegistryTrait
    Component -r-|> LanguageTrait
    Component -u-|> SettingsTrait
    Component -u-|> Repeater

    PackageTrait -u-|> Repeater
    SettingsTrait -u-|> Repeater

@enduml
