@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.serialization.jersey.json.project"
    
    Project <|-- SerializationJerseyJsonProject
    class SerializationJerseyJsonProject
    {
        --(constructors)--
        #SerializationJerseyJsonProject()
        --(serialization)--
        +SerializationJerseyJsonProject get()
    }
    
@enduml

