@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.application.project"
    
    Project <|-- CoreApplicationProject
    class CoreApplicationProject
    {
        --(constructors)--
        #CoreApplicationProject()
        --
        +CoreApplicationProject get()
    }
    
@enduml

