@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.serialization.kryo.project"
    
    Project <|-- SerializationKryoProject
    class SerializationKryoProject
    {
        --(constructors)--
        #SerializationKryoProject()
        --(serialization)--
        +SerializationKryoProject get()
    }
    
@enduml

