@startuml

    !include ../lexakai.theme
    
    title "com.telenav.kivakit.core.configuration.settings"
    
    class Settings
    {
        --(lookup)--
        +void register(Object settings)
        +T require(Class<T> settingsType)
        +T require(Class<T> settingsClass, PackagePath defaultSettingsPackage)
        +T require(Class<T> settingsType, Package defaultSettings)
    }
    
@enduml

