@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.configuration.project"
    
    Project <|-- CoreConfigurationProject
    class CoreConfigurationProject
    {
        --(constructors)--
        #CoreConfigurationProject()
        --(configuration)--
        +CoreConfigurationProject get()
    }
    
@enduml

