@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.array.bits.io.input"
    
    abstract BaseBitReader
    
    interface BitReader
    
    BitReader <|-- BaseBitReader
    abstract class BaseBitReader
    {
        --(constructors)--
        #BaseBitReader()
        #BaseBitReader(ByteList, Count)
        --
        #int mask()
        --(primitive)--
        #long byteCursor()
        #void byteCursor(long position)
        #boolean hasNextByte()
        #byte nextByte()
    }
    
    BaseBitReader <|-- BitInput
    class BitInput
    {
        --(constructors)--
        +BitInput(InputStream)
    }
    
    BitInput <|-- VariableReadSizeBitInput
    class VariableReadSizeBitInput
    {
        --(constructors)--
        +VariableReadSizeBitInput(InputStream)
        --(read)--
        +long readSigned()
        +long readUnsigned()
    }
    
@enduml

