@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.map.objects"
    
    PrimitiveMap <|-- LongToObjectMap
    class LongToObjectMap<T>
    {
        --(constructors)--
        #LongToObjectMap()
        +LongToObjectMap(String)
        --
        +T get(long key)
        --(collection)--
        +boolean containsKey(long key)
        +LongIterator keys()
        +boolean put(long key, T value)
        +void remove(long key)
        +Iterator<T> values()
    }
    
@enduml

