@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.array.scalars"
    
    abstract BaseStringConverter
    
    interface ByteList
    interface CharList
    interface ShortList
    interface LongList
    interface IntList
    
    PrimitiveArray <|-- ByteArray
    ByteList <|-- ByteArray
    class ByteArray
    {
        --(constructors)--
        #ByteArray()
        +ByteArray(String)
        --
        +int getUnsigned(int index)
        --(collection)--
        +boolean add(long value)
        --(conversion)--
        +String toBinaryString()
        +String toHexString()
    }
    
    PrimitiveArray <|-- CharArray
    CharList <|-- CharArray
    class CharArray
    {
        --(constructors)--
        #CharArray()
        +CharArray(String)
        --
        +int getUnsigned(int index)
        --(collection)--
        +char[] asArray()
        +void cursor(int cursor)
        +int cursor()
        +CharArray subArray(int index, int size)
    }
    
    BaseStringConverter <|-- CharArray.Converter
    class CharArray.Converter
    {
        --(constructors)--
        +Converter(Listener, Separators)
    }
    
    BaseStringConverter <|-- LongArray.Converter
    class LongArray.Converter
    {
        --(constructors)--
        +Converter(Listener, Separators)
    }
    
    BaseStringConverter <|-- ShortArray.Converter
    class ShortArray.Converter
    {
        --(constructors)--
        +Converter(Listener, Separators)
    }
    
    BaseStringConverter <|-- IntArray.Converter
    class IntArray.Converter
    {
        --(constructors)--
        +Converter(Listener, Separators)
    }
    
    PrimitiveArray <|-- IntArray
    IntList <|-- IntArray
    class IntArray
    {
        --(constructors)--
        #IntArray()
        +IntArray(String)
        --(collection)--
        +int[] asArray()
        +IntArray subArray(int index, int size)
    }
    
    PrimitiveArray <|-- LongArray
    LongList <|-- LongArray
    class LongArray
    {
        --(constructors)--
        #LongArray()
        +LongArray(String)
        --
        +void setBits(int index, long mask, long value)
        --(collection)--
        +long[] asArray()
        +LongArray subArray(int index, int size)
    }
    
    PrimitiveArray <|-- ShortArray
    ShortList <|-- ShortArray
    class ShortArray
    {
        --(constructors)--
        #ShortArray()
        +ShortArray(String)
        --
        +int getUnsigned(int index)
        --(collection)--
        +short[] asArray()
        +void cursor(int cursor)
        +int cursor()
        +ShortArray subArray(int index, int size)
    }
    
    PrimitiveSplitArray <|-- SplitByteArray
    ByteList <|-- SplitByteArray
    class SplitByteArray
    {
        --(constructors)--
        #SplitByteArray()
        +SplitByteArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitCharArray
    CharList <|-- SplitCharArray
    class SplitCharArray
    {
        --(constructors)--
        #SplitCharArray()
        +SplitCharArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitIntArray
    IntList <|-- SplitIntArray
    class SplitIntArray
    {
        --(constructors)--
        #SplitIntArray()
        +SplitIntArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitLongArray
    LongList <|-- SplitLongArray
    class SplitLongArray
    {
        --(constructors)--
        #SplitLongArray()
        +SplitLongArray(String)
    }
    
@enduml

