@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.map.multi.fixed"
    
    interface PrimitiveScalarMultiMap
    interface IntMultiMap
    interface LongMultiMap
    
    PrimitiveMultiMap <|-- IntToByteFixedMultiMap
    PrimitiveScalarMultiMap <|-- IntToByteFixedMultiMap
    class IntToByteFixedMultiMap
    {
        --(constructors)--
        #IntToByteFixedMultiMap()
        +IntToByteFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(int key)
        +ByteArray get(int key)
        +IntIterator keys()
        +void putAll(int key, ByteArray values)
        +void putAll(int key, byte[] values)
        +void putAll(long key, List<? extends Quantizable> values)
    }
    
    PrimitiveMultiMap <|-- IntToIntFixedMultiMap
    IntMultiMap <|-- IntToIntFixedMultiMap
    PrimitiveScalarMultiMap <|-- IntToIntFixedMultiMap
    class IntToIntFixedMultiMap
    {
        --(constructors)--
        #IntToIntFixedMultiMap()
        +IntToIntFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(int key)
        +IntArray get(int key)
        +IntIterator keys()
        +void putAll(int key, IntArray values)
        +void putAll(int key, int[] values)
    }
    
    PrimitiveMultiMap <|-- IntToLongFixedMultiMap
    LongMultiMap <|-- IntToLongFixedMultiMap
    PrimitiveScalarMultiMap <|-- IntToLongFixedMultiMap
    class IntToLongFixedMultiMap
    {
        --(constructors)--
        #IntToLongFixedMultiMap()
        +IntToLongFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(int key)
        +LongArray get(int key)
        +IntIterator keys()
        +void putAll(int key, long[] values)
        +void putAll(int key, LongArray values)
    }
    
    PrimitiveMultiMap <|-- IntToPackedArrayFixedMultiMap
    LongMultiMap <|-- IntToPackedArrayFixedMultiMap
    PrimitiveScalarMultiMap <|-- IntToPackedArrayFixedMultiMap
    class IntToPackedArrayFixedMultiMap
    {
        --(constructors)--
        #IntToPackedArrayFixedMultiMap()
        +IntToPackedArrayFixedMultiMap(String)
        --(collection)--
        +IntToPackedArrayFixedMultiMap bits(BitCount bits, PackedPrimitiveArray.OverflowHandling)
        +boolean containsKey(int key)
        +LongArray get(int key)
        +LongArray getSigned(int key)
        +IntIterator keys()
        +IntToPackedArrayFixedMultiMap listTerminator(long listTerminator)
        +void putAll(int key, long[] values)
        +void putAll(int key, LongArray values)
    }
    
    PrimitiveMultiMap <|-- LongToByteFixedMultiMap
    PrimitiveScalarMultiMap <|-- LongToByteFixedMultiMap
    class LongToByteFixedMultiMap
    {
        --(constructors)--
        #LongToByteFixedMultiMap()
        +LongToByteFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(long key)
        +ByteArray get(long key)
        +LongIterator keys()
        +void putAll(long key, List<? extends Quantizable> values)
        +void putAll(long key, byte[] values)
        +void putAll(long key, ByteArray values)
    }
    
    PrimitiveMultiMap <|-- LongToIntFixedMultiMap
    PrimitiveScalarMultiMap <|-- LongToIntFixedMultiMap
    class LongToIntFixedMultiMap
    {
        --(constructors)--
        #LongToIntFixedMultiMap()
        +LongToIntFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(long key)
        +IntArray get(long key)
        +LongIterator keys()
        +void putAll(long key, IntArray values)
        +void putAll(long key, List<? extends Quantizable> values)
        +void putAll(long key, int[] values)
    }
    
    PrimitiveMultiMap <|-- LongToLongFixedMultiMap
    PrimitiveScalarMultiMap <|-- LongToLongFixedMultiMap
    class LongToLongFixedMultiMap
    {
        --(constructors)--
        #LongToLongFixedMultiMap()
        +LongToLongFixedMultiMap(String)
        --(collection)--
        +boolean containsKey(long key)
        +LongArray get(long key)
        +LongIterator keys()
        +void putAll(long key, List<? extends Quantizable> values)
        +void putAll(long key, LongArray values)
        +void putAll(long key, long[] values)
    }
    
@enduml

