@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.batcher"
    
    abstract BaseRepeater
    
    interface Addable
    
    ArrayList <|-- Batcher.Batch
    class Batcher.Batch
    {
    }
    
    Addable <|-- Batcher.BatchAdder
    class Batcher.BatchAdder
    {
    }
    
    BaseRepeater <|-- Batcher
    abstract class Batcher<Element>
    {
        --(constructors)--
        #Batcher(String, Maximum, Count)
        --
        +BatchAdder adder()
        #void onBatch(Batch)
        --(lifecycle)--
        +void start(Count workers)
        +void stop()
    }
    
@enduml

