@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.list.store"
    
    PrimitiveListStore <|-- IntLinkedListStore
    class IntLinkedListStore
    {
        --(constructors)--
        #IntLinkedListStore()
        +IntLinkedListStore(String)
        --(collection)--
        +int add(int list, int value)
        +int addAll(int list, int[] values)
        +int addAll(int list, IntArray values)
        +int addAll(int list, List<? extends Quantizable> values)
        +IntIterator list(int list)
        +int remove(int list, int value)
    }
    
    PrimitiveListStore <|-- LongLinkedListStore
    class LongLinkedListStore
    {
        --(constructors)--
        #LongLinkedListStore()
        +LongLinkedListStore(String)
        --(collection)--
        +int add(int list, long value)
        +int addAll(int list, LongArray values)
        +int addAll(int list, List<? extends Quantizable> values)
        +int addAll(int list, long[] values)
        +LongIterator list(int list)
        +int remove(int list, long value)
    }
    
    PrimitiveCollection <|-- PackedStringStore
    class PackedStringStore
    {
        --(constructors)--
        #PackedStringStore()
        +PackedStringStore(String)
        --
        +String get(int index)
        +void set(int index, String value)
    }
    
    PrimitiveCollection <|-- PrimitiveListStore
    abstract class PrimitiveListStore
    {
        --(constructors)--
        #PrimitiveListStore()
        +PrimitiveListStore(String)
    }
    
@enduml

