@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.iteration"
    
    interface ByteIterable
    {
        --(primitive)--
        +ByteIterator iterator()
    }
    
    interface PrimitiveIterator
    PrimitiveIterator <|-- ByteIterator
    interface ByteIterator
    {
        --(collection)--
        +int hash()
        --(iteration)--
        +byte next()
    }
    
    interface CharIterable
    {
        --(primitive)--
        +CharIterator iterator()
    }
    
    interface PrimitiveIterator
    PrimitiveIterator <|-- CharIterator
    interface CharIterator
    {
        --(collection)--
        +int hash()
        --(iteration)--
        +char next()
    }
    
    interface IntIterable
    {
        --(primitive)--
        +IntIterator iterator()
    }
    
    interface PrimitiveIterator
    PrimitiveIterator <|-- IntIterator
    interface IntIterator
    {
        --(collection)--
        +int hash()
        --(iteration)--
        +int next()
    }
    
    interface LongIterable
    {
        --(primitive)--
        +LongIterator iterator()
    }
    
    interface PrimitiveIterator
    PrimitiveIterator <|-- LongIterator
    interface LongIterator
    {
        --(collection)--
        +int hash()
        --(iteration)--
        +long next()
    }
    
    interface PrimitiveIterator
    {
        --
        +boolean identical(PrimitiveIterator that)
        --(collection)--
        +int hashValue()
        --(iteration)--
        +boolean hasNext()
        +long nextLong()
    }
    
    interface ShortIterable
    {
        --(primitive)--
        +ShortIterator iterator()
    }
    
    interface PrimitiveIterator
    PrimitiveIterator <|-- ShortIterator
    interface ShortIterator
    {
        --(collection)--
        +int hash()
        --(iteration)--
        +short next()
    }
    
@enduml

