@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.array.bits.io"
    
    interface AutoCloseable
    AutoCloseable <|-- BitReader
    interface BitReader
    {
        --(collection)--
        +long cursor()
        +void cursor(long position)
        +int size()
        --(io)--
        +void onClose()
        --(iteration)--
        +boolean hasNext()
        --(read)--
        +int read(int bits)
        +boolean readBit()
        +int readFlexibleInt(int smallBitCount, int bigBitCount)
        +long readLong(int bits)
        +String readString()
    }
    
    interface AutoCloseable
    AutoCloseable <|-- BitWriter
    interface BitWriter
    {
        --(collection)--
        +long cursor()
        --(io)--
        +void flush()
        +void onClose()
        --(write)--
        +void write(long value, int bits)
        +boolean writeBit(boolean bit)
        +void writeByte(byte value)
        +void writeFlexibleInt(int smallBitCount, int bigBitCount, int value)
        +void writeInt(int value)
        +void writeString(String value)
    }
    
@enduml

