@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.map.scalars"
    
    interface PrimitiveScalarMap
    
    interface IntToIntMap.EntryVisitor
    {
        --
        +void onEntry(long key, int value)
    }
    
    interface IntToLongMap.EntryVisitor
    {
        --
        +void onEntry(long key, long value)
    }
    
    interface LongToByteMap.EntryVisitor
    {
        --
        +void onEntry(long key, byte value)
    }
    
    interface LongToIntMap.EntryVisitor
    {
        --
        +void onEntry(long key, int value)
    }
    
    interface LongToLongMap.EntryVisitor
    {
        --
        +void onEntry(long key, long value)
    }
    
    interface IntToByteMap.EntryVisitor
    {
        --
        +void onEntry(long key, byte value)
    }
    
    PrimitiveMap <|-- IntToByteMap
    PrimitiveScalarMap <|-- IntToByteMap
    class IntToByteMap
    {
        --(constructors)--
        #IntToByteMap()
        +IntToByteMap(String)
        --
        +void entries(EntryVisitor)
        +byte get(int key)
        --(collection)--
        +boolean containsKey(int key)
        +IntIterator keys()
        +boolean put(int key, byte value)
        +boolean remove(int key)
        +ByteIterator values()
        --(math)--
        +void increment(int key)
    }
    
    PrimitiveMap <|-- IntToIntMap
    PrimitiveScalarMap <|-- IntToIntMap
    class IntToIntMap
    {
        --(constructors)--
        #IntToIntMap()
        +IntToIntMap(String)
        --
        +void entries(EntryVisitor)
        +int get(int key)
        --(collection)--
        +boolean containsKey(int key)
        +IntIterator keys()
        +boolean put(int key, int value)
        +boolean remove(int key)
        +IntIterator values()
        --(math)--
        +void increment(int key)
    }
    
    PrimitiveMap <|-- IntToLongMap
    PrimitiveScalarMap <|-- IntToLongMap
    class IntToLongMap
    {
        --(constructors)--
        #IntToLongMap()
        +IntToLongMap(String)
        --
        +void entries(EntryVisitor)
        +long get(int key)
        --(collection)--
        +boolean containsKey(int key)
        +IntIterator keys()
        +boolean put(int key, long value)
        +boolean remove(int key)
        +LongIterator values()
        --(math)--
        +void increment(int key)
    }
    
    PrimitiveMap <|-- LongToByteMap
    PrimitiveScalarMap <|-- LongToByteMap
    class LongToByteMap
    {
        --(constructors)--
        #LongToByteMap()
        +LongToByteMap(String)
        --
        +void entries(EntryVisitor)
        +byte get(long key)
        --(collection)--
        +boolean containsKey(long key)
        +LongIterator keys()
        +boolean put(long key, byte value)
        +boolean remove(long key)
        +ByteIterator values()
        --(math)--
        +void increment(long key)
    }
    
    PrimitiveMap <|-- LongToIntMap
    PrimitiveScalarMap <|-- LongToIntMap
    class LongToIntMap
    {
        --(constructors)--
        #LongToIntMap()
        +LongToIntMap(String)
        --
        +void entries(EntryVisitor)
        +int get(long key)
        --(collection)--
        +boolean containsKey(long key)
        +LongIterator keys()
        +boolean put(long key, int value)
        +boolean remove(long key)
        +IntIterator values()
        --(math)--
        +void increment(long key)
    }
    
    PrimitiveMap <|-- LongToLongMap
    PrimitiveScalarMap <|-- LongToLongMap
    class LongToLongMap
    {
        --(constructors)--
        #LongToLongMap()
        +LongToLongMap(String)
        --
        +void entries(EntryVisitor)
        +long get(long key)
        --(collection)--
        +boolean containsKey(long key)
        +LongIterator keys()
        +boolean put(long key, long value)
        +boolean remove(long key)
        +LongIterator values()
        --(math)--
        +void increment(long key)
    }
    
    PrimitiveMap <|-- StringToIntMap
    class StringToIntMap
    {
        --(constructors)--
        #StringToIntMap()
        +StringToIntMap(String)
        --
        +int get(String key)
        --(collection)--
        +boolean containsKey(String key)
        +Iterator<String> keys()
        +boolean put(String key, int value)
        +boolean remove(String key)
        +IntIterator values()
    }
    
    PrimitiveMap <|-- StringToObjectMap
    class StringToObjectMap<T>
    {
        --(constructors)--
        #StringToObjectMap()
        +StringToObjectMap(String)
        --
        +T get(String key)
        --(collection)--
        +boolean containsKey(String key)
        +Iterator<String> keys()
        +void put(String key, T value)
        +boolean remove(String key)
        +Iterator<T> values()
    }
    
@enduml

