@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.array.bits.io.output"
    
    abstract BaseBitWriter
    
    interface BitWriter
    
    BitWriter <|-- BaseBitWriter
    abstract class BaseBitWriter
    {
        --(io)--
        #void onFlush(byte value)
        --(write)--
        #void onWrite(byte value)
    }
    
    BaseBitWriter <|-- BitOutput
    class BitOutput
    {
        --(constructors)--
        +BitOutput(OutputStream)
    }
    
@enduml

