@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.core.collections.primitive.array.strings"
    
    PrimitiveArray <|-- PackedStringArray
    class PackedStringArray
    {
        --(constructors)--
        #PackedStringArray()
        +PackedStringArray(String)
        --
        +String get(int identifier)
        +String safeGet(int identifier)
        --(math)--
        +int add(String)
        +void maximumStringLength(int maximumStringLength)
    }
    
    enum PackedStringArray.Type
    {
        ASCII
        UNICODE
    }
    
@enduml

