@startuml

    !include ../lexakai/lexakai.theme
    
    title "Split Primitive Arrays"
    
    interface ByteList
    interface CharList
    interface PackedPrimitiveArray
    interface LongList
    interface IntList
    
    PrimitiveArray <|-- PrimitiveSplitArray
    abstract class PrimitiveSplitArray
    {
        --(constructors)--
        #PrimitiveSplitArray()
        #PrimitiveSplitArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitByteArray
    ByteList <|-- SplitByteArray
    class SplitByteArray
    {
        --(constructors)--
        #SplitByteArray()
        +SplitByteArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitCharArray
    CharList <|-- SplitCharArray
    class SplitCharArray
    {
        --(constructors)--
        #SplitCharArray()
        +SplitCharArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitIntArray
    IntList <|-- SplitIntArray
    class SplitIntArray
    {
        --(constructors)--
        #SplitIntArray()
        +SplitIntArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitLongArray
    LongList <|-- SplitLongArray
    class SplitLongArray
    {
        --(constructors)--
        #SplitLongArray()
        +SplitLongArray(String)
    }
    
    PrimitiveSplitArray <|-- SplitPackedArray
    LongList <|-- SplitPackedArray
    PackedPrimitiveArray <|-- SplitPackedArray
    class SplitPackedArray
    {
        --(constructors)--
        #SplitPackedArray()
        +SplitPackedArray(String)
        --
        +boolean getBoolean(int index)
        +long getSigned(int index)
        +boolean safeGetBoolean(int index)
        +void setBoolean(int index, boolean value)
        --(collection)--
        +Count getCount(int index)
        +Count safeGetCount(int index)
        +void setCount(int index, Count)
        --(filesystem)--
        +void copyTo(SplitPackedArray that)
        --(lifecycle)--
        +void initializeElements(boolean initializeElements)
        --(primitive)--
        +int safeGetInt(int index)
        +void setInt(int index, int value)
    }
    
@enduml

