@startuml

    !include ../lexakai/lexakai.theme
    
    title "Primitive Lists"
    
    interface ByteCollection
    interface CompressibleCollection
    interface PrimitiveList
    ByteCollection <|-- ByteList
    PrimitiveList <|-- ByteList
    CompressibleCollection <|-- ByteList
    interface ByteList
    {
        --
        +byte get(int index)
        +byte safeGet(int index)
        +void set(int index, byte value)
        --(collection)--
        +byte[] asArray()
        +void clear(int index)
        +void cursor(int position)
        +int cursor()
        +byte first()
        +byte last()
        --(iteration)--
        +boolean hasNext()
        +byte next()
        --(lifecycle)--
        +void reset()
        --(primitive)--
        +char readFlexibleChar()
        +short readFlexibleShort()
        +int readInt()
        +ByteList sublist(int offset, int size)
        +void writeFlexibleChar(char value)
        +void writeFlexibleShort(short value)
        +void writeInt(int value)
        --(read)--
        +byte read()
        +boolean[] readBooleans(int size)
        +int readUnsigned()
        --(search)--
        +int binarySearch(byte target)
        --(write)--
        +void write(byte value)
        +void writeBooleans(boolean[] values)
    }
    
    interface CharCollection
    interface PrimitiveList
    CharCollection <|-- CharList
    PrimitiveList <|-- CharList
    interface CharList
    {
        --
        +char get(int index)
        +char safeGet(int index)
        +void set(int index, char value)
        --(collection)--
        +void clear(int index)
        +char first()
        +char last()
        --(search)--
        +int binarySearch(char target)
    }
    
    PrimitiveListStore <|-- IntLinkedListStore
    class IntLinkedListStore
    {
        --(constructors)--
        #IntLinkedListStore()
        +IntLinkedListStore(String)
        --(collection)--
        +int add(int list, int value)
        +int addAll(int list, int[] values)
        +int addAll(int list, IntArray values)
        +int addAll(int list, List<? extends Quantizable> values)
        +IntIterator list(int list)
        +int remove(int list, int value)
    }
    
    interface IntCollection
    interface PrimitiveList
    IntCollection <|-- IntList
    PrimitiveList <|-- IntList
    interface IntList
    {
        --
        +int get(int index)
        +int safeGet(int index)
        +void set(int index, int value)
        --(collection)--
        +void clear(int index)
        +void cursor(int position)
        +int cursor()
        +int first()
        +int last()
        --(search)--
        +int binarySearch(int target)
        --(write)--
        +void write(int value)
    }
    
    PrimitiveListStore <|-- LongLinkedListStore
    class LongLinkedListStore
    {
        --(constructors)--
        #LongLinkedListStore()
        +LongLinkedListStore(String)
        --(collection)--
        +int add(int list, long value)
        +int addAll(int list, LongArray values)
        +int addAll(int list, List<? extends Quantizable> values)
        +int addAll(int list, long[] values)
        +LongIterator list(int list)
        +int remove(int list, long value)
    }
    
    interface LongCollection
    interface PrimitiveList
    LongCollection <|-- LongList
    PrimitiveList <|-- LongList
    interface LongList
    {
        --
        +long get(int index)
        +long safeGet(int index)
        +void set(int index, long value)
        --(collection)--
        +void clear(int index)
        +void cursor(int position)
        +int cursor()
        +long first()
        +long last()
        --(search)--
        +int binarySearch(long target)
    }
    
    PrimitiveCollection <|-- PackedStringStore
    class PackedStringStore
    {
        --(constructors)--
        #PackedStringStore()
        +PackedStringStore(String)
        --
        +String get(int index)
        +void set(int index, String value)
    }
    
    interface Sized
    Sized <|-- PrimitiveList
    interface PrimitiveList
    {
        --
        +long getPrimitive(int index)
        +long safeGetPrimitive(int index)
        +void setPrimitive(int index, long value)
        --(checks)--
        +boolean isPrimitiveNull(long value)
        --(collection)--
        +ObjectList<T> asList(LongMapFactory<T>)
        +Count capacity()
    }
    
    PrimitiveCollection <|-- PrimitiveListStore
    abstract class PrimitiveListStore
    {
        --(constructors)--
        #PrimitiveListStore()
        +PrimitiveListStore(String)
    }
    
    interface PrimitiveList
    interface ShortCollection
    ShortCollection <|-- ShortList
    PrimitiveList <|-- ShortList
    interface ShortList
    {
        --
        +short get(int index)
        +short safeGet(int index)
        +void set(int index, short value)
        --(collection)--
        +void clear(int index)
        +short first()
        +short last()
        --(search)--
        +int binarySearch(short target)
    }
    
@enduml

