@startuml

    !include ../lexakai/lexakai.theme
    
    title "Batch Processing"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- Batcher
    abstract class Batcher<Element>
    {
        --(constructors)--
        #Batcher(String, Maximum, Count)
        --
        +BatchAdder adder()
        #void onBatch(Batch)
        --(lifecycle)--
        +void start(Count workers)
        +void stop()
    }
    
@enduml

