name: Check Markdown links

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '!**/*.md'
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
